### ISSUE TITLE
Warning: Detected multiple renderers concurrently rendering the same context provider. This is currently unsupported. 

### ISSUE THREAD

**Issue by ccc159** [brianzinn/react-babylonjs#100]
Hi @brianzinn,

I have this warning everytime a babylon component is rendered. Is it because I'm using ContextAPI and `react-babylonjs` complaints about it?

![image](https://user-images.githubusercontent.com/15573101/99901964-a9d85b80-2cba-11eb-9be1-fb8bd60622bc.png)

Is it a serious problem? If so, how can I fix it? If not, how can I suppress this error message?

**Comment by brianzinn** [comment]
It's safe to ignore if everything is working as expected.  I need to fix something in the renderer - looks like as a secondary renderer is not cleared out when the scene changes.  I will investigate.  Thank-you for reporting.

**Comment by brianzinn** [comment]
@ccc159  I've fixed it on the v3 branch, which should be available in next couple of weeks.  If you need it ported to current version can make it happen.

**Comment by ccc159** [comment]
Super, thanks a lot!

**Comment by danielpaz6** [comment]
@brianzinn Is there a release date for v3? I face that problem as well.

**Comment by brianzinn** [comment]
hi @danielpaz6 it's fixed on the last couple beta releases ie: `yarn add react-babylonjs@latest`.  I just fixed Model finally and have tested it against a few projects and it looks good.  I think the only work left is to document the breaking changes from 2.x in readme, but most are documented here:
https://github.com/brianzinn/react-babylonjs/discussions/107
It will be out before end of week for sure.  December was too busy.  Thanks for reminder!
