### ISSUE TITLE
Type errors for fromInstance and source props

### ISSUE THREAD

**Issue by nturley** [brianzinn/react-babylonjs#101]
It looks like I'm getting props type errors for `fromInstance`, and `source`. The code executes just fine so I assume it's just a typing issue and not a functional issue.

Issue seems to be present in version 2.3.1 even though `fromInstance` support was added around 2.2.8 and instancedMesh was added around 2.2.7.

I'm guessing these props are missing from [generatedProps.ts](https://github.com/brianzinn/react-babylonjs/blob/master/src/generatedProps.ts)?

I'm happy to contribute a PR but I was having a hard time understanding how the codegen works. If you point me in the right direction, I could take a crack at it.

## Screenshots
![image](https://user-images.githubusercontent.com/2446659/100024794-1895e180-2dad-11eb-92b8-2b57565e9018.png)
![image](https://user-images.githubusercontent.com/2446659/100024811-20ee1c80-2dad-11eb-9383-c13ca8912f56.png)
![image](https://user-images.githubusercontent.com/2446659/100024845-319e9280-2dad-11eb-8461-4791ed3a17a4.png)

## Minimal Example
https://stackblitz.com/edit/react-ts-wxuhxh?file=index.tsx

**Comment by brianzinn** [comment]
hi @nturley thanks for reporting.  I think it's outside of the codegen.  I union the allowed props for each type with `CustomProps`, so I should have added it there and that should be cleaned up to be more restrictive actually :)
https://github.com/brianzinn/react-babylonjs/blob/40412ad5056b51d96aef2386f2cd649d53d899f0/src/CreatedInstance.ts#L27

That will include it automatically in the JSX intrinsic elements everywhere :)
