### ISSUE TITLE
Instantiate Mesh Hierarchies 

### ISSUE THREAD

**Issue by nturley** [brianzinn/react-babylonjs#104]
So, I have a bunch of gltf models and each is a hierarchy of Meshes, InstancedMeshes, and TransformNodes and I would like to add it to my scene a bunch of times.

For example
```JSX
Array.from(Array(100)).map((_, i) => 
<model
  rootUrl="https://neilturley.dev/game-assets/kenney_hexagonkit_1/Models/GLTF%20format/"
  sceneFilename="building_sheep.glb"
  position={new Vector3(i,0,0)}
  key={i}
/>);
```
That's the easy way to write it but it's super slow. So I'm experimenting with different ways to make this work. I'm kinda surprised there isn't a simple pattern because this doesn't seem that uncommon of a thing to do.

So a few quick questions.

1. If I do `<mesh fromInstance={foo.clone()}/>`, will the life cycle management also dispose of all of the children of foo or do I need to walk the tree myself to attach them all to React components?
2. The clone() method apparently creates Meshes instead of InstancedMeshes. I don't suppose you know of a way to do a clone with InstanceMeshes? I tried playing with AssetManagers and AssetContainers but none of them seem to work.

**Comment by brianzinn** [comment]
hi @nturley - sorry for the delayed response.  To do what you are after definitely don't use the `<model />` jsx (unless you take onModelLoaded as a ref).  Your best bet is to use the asset loader and then call `createInstance` on that.  Here are a couple of links and then I will answer your questions:
https://playground.babylonjs.com/#0K8EYN#0 (instancing loaded meshes)
https://doc.babylonjs.com/divingDeeper/mesh/copies/thinInstances (thin instances new in 4.2)

1. `<mesh fromInstance={...} />` that will call dispose, but I am changing the behaviour to not dispose by default.  In v3 there will be a new property to continue disposing - likely `disposeOnUnmount`, which will default to false.
2. You can use `createInstance` method (from the playground link above).  You will want to do so from the main mesh, which you can just keep a reference to.

There is also an `instancedMesh` option, which essentially adds an instance to the source mesh.  There is a storybook here with hundreds of instances:
source: `https://brianzinn.github.io/react-babylonjs/?path=/story/babylon-basic--instances`
code: `https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/Basic/instances.stories.js#L75`

There is a big improvement in v3 as well for AssetManager and SceneLoader to load assets with Suspense - it will make what you are trying to do a little easier.

If there is a syntax specifically declarative that you think would be intuitive then I can work on one with you.  I have definitely done a lot with instancing to speed up my games!

**Comment by nturley** [comment]
> You can use createInstance method (from the playground link above). You will want to do so from the main mesh, which you can just keep a reference to.

I don't think createInstance also instances the child Nodes. See this example.

```JSX
const [mesh2, setMesh2] = useState(null);
...
<sphere
  name="x"
  position={new Vector3(0,0,1)}
  ref={setMesh2}
>
  <box
    name="y"
    width={0.5}/>
</sphere>
{mesh2 && (
<InstancedMesh
  fromInstance={mesh2.hostInstance.createInstance()}
  position={new Vector3(0, 0, -1)}
/>
)}
```

![image](https://user-images.githubusercontent.com/2446659/100678328-83599680-3332-11eb-8f62-554f1b28e224.png)

It only created an instance of the parent.

**Comment by brianzinn** [comment]
The parameter for instancedMesh is 'source'.  What you have works there - I think only because InstancedMesh derives from AbstractMesh - you would need to look in the constructor to see what else is missing from how you have done it (https://github.com/BabylonJS/Babylon.js/blob/master/src/Meshes/instancedMesh.ts#L44).  Have a look at the source link provided, but also `source` parameter here:
https://www.babylonjs.com.cn/api/classes/babylon-240.html#constructor

I think it should be:
```
<instancedMesh
  source={mesh2.hostInstance}
  position={new Vector3(0, 0, -1)}
/>
```

Notice in the "dude" playground above that each mesh calls `createInstance` for each mesh - I'm not sure that what you are asking for is possible.  I don't see any options for instancing also child meshes.

To be honest I have never instanced meshes in that way, so we may need a general answer that we could post in the forum and then revisit how to do so declaratively?

**Comment by brianzinn** [comment]
I'm happy to dig into this further also come up with a declarative syntax.  Going to close, but please re-open if the above didn't work for you.  With the new hooks in 3.0 it should be possible to memoize the results and create many instances that perform the same as the imperative playground.
