### ISSUE TITLE
Question: is there a good way to create materials imperatively?

### ISSUE THREAD

**Issue by alexhoma** [brianzinn/react-babylonjs#117]
I know this question is not fully related with the `react-babylon` development, but I want to know it if it's possible. The case I raise is the following:

1. I'm trying to create a material into a React component imperatively, like the example below (It is a very dumb example just for simplicity sake).

```javascript
function Cable({ mesh, color }) {
     const scene = useScene();
     const material = new PBRMaterial('cable', scene);
     material.albedoColor = Color3.FromHexString(color);
     
     return <mesh fromInstance={mesh} material={material} />
}
```

2. And what I see in the debugger, is that my "cable" material is cloned every time the props of the component change:

![image](https://user-images.githubusercontent.com/7917771/105895735-2b7b9b00-6016-11eb-894f-863c33b529c3.png)

Of course this makes totally sense since React renders the component every time a prop changes, and the `PBRMaterial`  instance is created again and again. **But the question is:** 

- how it is possible to solve imperative code like this in `react-babylon` without multiple instance creations? 
- or how does react-babylon handles this in its core?

I tried with `useState` and similar workarounds to avoid this behavior but it doesn't work as expected. (I can show them if necessary)

**Comment by brianzinn** [comment]
hi @alexhoma good questions -  keep them coming!  It shows there is work to be done on the documentation.  Materials automatically assign themselves to their parent meshes.  I think you just need to go like this (untested 🤞):
```jsx
function Cable({ mesh, color }) {
     return <mesh fromInstance={mesh}>
           <pbrMaterial name="cable" albedoColor={Color3.FromHexString(color)} />
      </mesh>
}
```

If you wanted a more imperative solution with `useState` did you try with a function (only color is re-assigned on prop updates)?
```jsx
function Cable({ mesh, color }) {
     const scene = useScene();
     const [pbrMaterial] = useState(() => {
        return new PBRMaterial('cable', scene);
     });
     pbrMaterial.albedoColor = Color3.FromHexString(color);
     
     return <mesh fromInstance={mesh} material={pbrMaterial} />
 }
```

There are some examples in this storybook that show also how to assign textures (also see `assignTo` custom prop and why I was proposing `assignFrom`), but also PBRMaterial to mesh.
`https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/Textures/pbr.stories.js`

If those solutions don't work just provide more details 😄

**Comment by alexhoma** [comment]
It works like a charm! I didn't know that `useState`  accepts a callback function as an argument that will only be executed once. This is why even using the state hook, the `new PBRMaterial` was being instanced at every render.

Thank you! :smile:
