### ISSUE TITLE
onModelLoaded ILoadedModel / LoadedModel

### ISSUE THREAD

**Issue by dennemark** [brianzinn/react-babylonjs#120]
Hi,

it seems there has been a breaking change with Model in v3. I was wondering, why Model onModelLoaded gives back an interface, instead of the loaded model? onModelError however uses LoadedModel. In v2 I had one case where I was disposing the loaded model after processing it, however this is only possible with LoadedModel containing a mesh.

Best,
Martin

![image](https://user-images.githubusercontent.com/29654902/108087875-27242a00-7078-11eb-80f9-18e7e9dcc0f1.png)

**Comment by brianzinn** [comment]
thanks for reporting @dennemark -- I'll extend the interface.  Good catch :)  Also, will change `onModelError` to match.

**Comment by brianzinn** [comment]
can you try `3.0.9`?  I hope that resolves the typings issue...

**Comment by dennemark** [comment]
Hi!
thanks for the fast push! However, I would have thought both events can have either LoadedModel or ILoadedModel. In earlier version I had access to LoadedModel and could even use functions like dispose on the model, however with ILoadedModel this is not possible. Could you explain why ILoadedModel is used? I do not fully understand it.
