### ISSUE TITLE
Lagging when using drag&drop feature

### ISSUE THREAD

**Issue by mariuszzieja** [brianzinn/react-babylonjs#121]
When dragging and moving boxes from storybook:
[https://brianzinn.github.io/react-babylonjs/?path=/story/behaviors--drag-n-drop](https://brianzinn.github.io/react-babylonjs/?path=/story/behaviors--drag-n-drop)
there is noticeable lag when compared to original babylonjs example:
[https://www.babylonjs.com/demos/dragndrop/](https://www.babylonjs.com/demos/dragndrop/)

**Comment by brianzinn** [comment]
There is definitely a lag and that is the default behavior.  The underlying code is quite a bit different as well.  Here is the part of dragndrop code that does the movement in the official demo:
```javascript
var startingPoint;
    var currentMesh;
    var getGroundPosition = function(evt) {
        var pickinfo = scene.pick(scene.pointerX, scene.pointerY, function(mesh) {
            return mesh == ground
        });
        if (pickinfo.hit) {
            return pickinfo.pickedPoint
        }
        return null
    };
    var onPointerDown = function(evt) {
        if (evt.button !== 0) {
            return
        }
        var pickInfo = scene.pick(scene.pointerX, scene.pointerY, function(mesh) {
            return mesh !== ground
        });
        if (pickInfo.hit) {
            currentMesh = pickInfo.pickedMesh;
            startingPoint = getGroundPosition(evt);
            if (startingPoint) {
                setTimeout(function() {
                    camera.detachControl(canvas)
                }, 0)
            }
        }
    };
    var onPointerUp = function() {
        if (startingPoint) {
            camera.attachControl(canvas);
            startingPoint = null;
            return
        }
    };
    var onPointerMove = function(evt) {
        if (!startingPoint) {
            return
        }
        var current = getGroundPosition(evt);
        if (!current) {
            return
        }
        var diff = current.subtract(startingPoint);
        currentMesh.position.addInPlace(diff);
        startingPoint = current
    };
    canvas.addEventListener("pointerdown", onPointerDown, false);
    canvas.addEventListener("pointerup", onPointerUp, false);
    canvas.addEventListener("pointermove", onPointerMove, false);
    scene.onDispose = function() {
        canvas.removeEventListener("pointerdown", onPointerDown);
        canvas.removeEventListener("pointerup", onPointerUp);
        canvas.removeEventListener("pointermove", onPointerMove)
    }
    ;
    return scene
```

The pointerdrag behaviour though is different https://doc.babylonjs.com/divingDeeper/behaviors/meshBehaviors#pointerdragbehavior

You can reduce the "lagging" by changing the LERP ratio, which defaults to 0.2 to 1.0 (or anywhere inbetween):
https://github.com/BabylonJS/Babylon.js/blob/master/src/Behaviors/Meshes/pointerDragBehavior.ts#L243
```jsx
<sphere ...>
   <standardMaterial ... />
   <pointerDragBehavior ... dragDeltaRatio={1.0} />
</sphere>
```

If you go back on that story commit history - the original version was not declarative and had all of that original code from the demo - it was changed when support for Behaviors was added :)  Let me know if that answers your question.  Cheers.

**Comment by mariuszzieja** [comment]
> Let me know if that answers your question. Cheers.
Yes it does! Thank you :)
