### ISSUE TITLE
redux store context not being passed through babylon react components?

### ISSUE THREAD

**Issue by kyehuelin** [brianzinn/react-babylonjs#126]
Hi, as per the docs for redux toolkit setup

I have a redux store that is setup in the usual way

```
import { Provider } from "react-redux";

ReactDOM.render(
  <Provider store={store}>
          <App />
  </Provider>,
  document.getElementById("root")
);
```

when i use regular react components i can use the hook to get the state from the store no problem

`const rootState = useAppSelector((rState) => rState); // access root state: combined slices`

but when i try to use these hooks in babylon react components i get
`Error: could not find react-redux context value; please ensure the component is wrapped in a <Provider>`

id there a work around or something i am doing wrong?

**Comment by brianzinn** [comment]
hi @kyehuelin - This catches so many people!  It's unfortunate the React team never came up with a solution.  You need to bridge the context.  Here are some code samples:
https://github.com/konvajs/react-konva/issues/188

I have an example in storybook for bridging the context:
https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/Basic/contextBridge.stories.js

You can also flow the props through, but is only a reasonable solution with few props/methods:
https://github.com/brianzinn/create-react-app-babylonjs/blob/master/src/withProps/components/WithProps.js

**Comment by Chargeuk** [comment]
Hi @brianzinn 
Am I correct in thinking that we need to bridge the react-babylonjs scene component for redux in the same way that the following react-konva example bridges the stage component? Thanks

https://github.com/konvajs/react-konva/issues/311#issuecomment-454411007

**Comment by brianzinn** [comment]
Yes, that's how the bridge is made!  It's not ideal 😞 If you are not really far down the redux path and using middleware, etc - there are other state management options like zustand that handle the context loss across renderer boundaries.

**Comment by kyehuelin** [comment]
Appreciate you getting back to me @brianzinn. 
Now i know whats going ive realised that i can jsut setup my sceneStore at the root of the scene. and have a siteStore at the root of the app sepereately, If in the future I have a use case where the bridge needs crossing i will implement what youve done. 

on a side not. are you aware if recoil https://recoiljs.org state managment has the same context bridging issue?

Thanks.

**Comment by brianzinn** [comment]
yes it does use the context, so suffers the same fate:
https://github.com/facebookexperimental/Recoil/blob/master/src/hooks/Recoil_useRecoilBridgeAcrossReactRoots.js

**Comment by brianzinn** [comment]
Closing from inactivity and it looks resolved - please re-open if you have more questions or comments.
