### ISSUE TITLE
fontAwesome icon only showing after pointer roll over

### ISSUE THREAD

**Issue by kyehuelin** [brianzinn/react-babylonjs#127]
I saw your FontAwesome storybook example on the gui

I implemented ike this

App.css
```

@font-face {
    font-family: 'FontAwesome';
    src: local('FontAwesome'), url(../node_modules/@fortawesome/fontawesome-pro/webfonts/fa-regular-400.woff) format('woff');
  }
```

Gui.tsx

```
          <babylon-button
            horizontalAlignment={1}
            thickness={0}
            background="red"
            widthInPixels={70}
            height={1}
          >
            <textBlock text={"\uf00d"} fontFamily="FontAwesome" fontSize={24} color="black" />
          </babylon-button>
```
on initial load
![image](https://user-images.githubusercontent.com/20302965/115369534-67c42f00-a1f2-11eb-8cb7-f31d6ca9dcc6.png)

afeter i roll over button
![image](https://user-images.githubusercontent.com/20302965/115369618-80cce000-a1f2-11eb-92a3-5e49df3955c9.png)

any idea whats going on here? thanks.

**Comment by brianzinn** [comment]
I think your font is not loaded on initial draw and on the rollover that the texture is redrawn (at that point the font is "loaded").  I think you would need something like a font observer and then to trigger something on the GUI/ADT.  That would be a good  feature for the main library actually - watch for missing fonts and redraw tree when loaded. 

What do you see if you run something like this:
```javascript
document.fonts.onloadingdone = function (fontFaceSetEvent) {
   alert('onloadingdone we have ' + fontFaceSetEvent.fontfaces.length + ' font faces loaded');
};
```

**Comment by kyehuelin** [comment]
thanks for reply, so document.fonts I believe is counted as experimental meaning I cant use document.fonts in my environment I was able to hack something in from here:

https://github.com/Microsoft/TypeScript/issues/30984

I was then able in a very hacky way. do this, which actually works, but isnt great

```
  const [fontsReady, setFontsReady] = useState(false);

  document.fonts.load("16px FontAwesome").then(() => {
    setFontsReady(true);
  });
```

```
            {fontsReady && (
              <textBlock text={"\uf00d"} fontFamily="FontAwesome" fontSize={24} color="black" />
            )}
```

**Comment by brianzinn** [comment]
@kyehuelin - Interesting find. We should ask in main forum - would be interesting to see if they would be interested in a built-in solution.  I played around with what you have and tested out a fallback while the font is loading (timeout is there just for visualization purposes):
```jsx
const [fontsReady, setFontsReady] = useState(false);
const adtRef = useRef<AdvancedDynamicTexture | null>(null);
const faLoaded = useRef(false);
document.fonts.load("16px FontAwesome").then(() => {
  if (faLoaded.current !== true && adtRef.current !== null) {
    faLoaded.current = true;

    setTimeout(() => {
      setFontsReady(true);
      adtRef.current!.markAsDirty();
    }, 1000);
  }
});

return (
   <advancedDynamicTexture ref={adtRef} ...>
     ...
     <textBlock text={`${fontsReady ? '\uf00d' : 'X'} click me`} fontFamily='FontAwesome' ... />
     ...
   </advancedDynamicTexture>
)
```

I tried to set the fontFamily, but it looked like it didn't trigger a redraw, but I would need to test more.  I feel like this should be handled transparently by a font observer and a simpler way would be on the ADT itself...

**Comment by brianzinn** [comment]
I think i'll mark this as closed, but feel free to re-open and we could work on a solution.

One interesting thing we could add is a hook that you can attach to a ref (that is a control or AdvancedDynamicTexture).  And it wraps the font loading code and I think you just need to call `_markAsDirty()` on the (root) rectangle that is created for the GUI and it should force a redraw - I think my mistake above was calling it on the ADT.  That wouldn't trigger changing the text like example in my previous comment.
