### ISSUE TITLE
Adding image as material to 3d cuboid

### ISSUE THREAD

**Issue by crossLineApex** [brianzinn/react-babylonjs#128]
Hey I have a url of an image which I then want to mesh to a cuboid. How should I do it ? I have tried a lot of stuffs

**Comment by brianzinn** [comment]
@crossLineApex  Would something like the Skybox work?
https://github.com/brianzinn/react-babylonjs/blob/master/src/customComponents/Skybox.tsx

Otherwise provide the regular code and we can see if there is a declarative equivalent.

**Comment by crossLineApex** [comment]
So my exact project is to take screenshot og a map and render it to as a material to a cuboid.
Below is my code where I'm able to render a cuboid successfully. Now I need to send a prop here which is an image url and mesh it to the cuboid. But I'm unable to find a concrete solution after looking through the docs.

import React, { useRef, useState } from "react";
import {
  Engine,
  Scene,
  useBeforeRender,
  useClick,
  useHover
} from "react-babylonjs";
import { Vector3, Color3 } from "@babylonjs/core";

const SpinningBox = (props) => {
  const boxRef = useRef(null);

  return (
    <box
      name={props.name}
      ref={boxRef}
      size={2}
      position={props.position}
      height={1}
      width={0.75}
      depth={0.25}
    ></box>
  );
};

export const SceneWithSpinningBoxes = () => (
  <div>
    <Engine antialias adaptToDeviceRatio canvasId="babylonJS">
      <Scene>
        <arcRotateCamera
          name="camera1"
          target={Vector3.Zero()}
          alpha={(3 * Math.PI) / 4}
          beta={Math.PI / 4}
          radius={2}
        />
        <hemisphericLight
          name="light1"
          intensity={0.7}
          direction={Vector3.Up()}
        />
        <SpinningBox
          name="left"
          position={new Vector3(0, 0, 0)}
          color={Color3.FromHexString("#EEB5EB")}
        />
      </Scene>
    </Engine>
  </div>
);

export default SceneWithSpinningBoxes;

**Comment by crossLineApex** [comment]
I'm using React along with react-babylonjs, @babylonjs/core and @babylonjs/gui. My main task is to pass a url to this component and mesh it to a cuboid. Now I was just focusing on getting a cuboid which I'm able to do in the below code. How should I go around and mesh an url image which I may get from a prop. For now you can use any image url without using any props and mesh it to the cuboid.

You can also check my codesandbox here : https://codesandbox.io/s/divine-silence-ek9p5

import React, { useRef, useState } from "react";
import {
  Engine,
  Scene,
  useBeforeRender,
  useClick,
  useHover
} from "react-babylonjs";
import { Vector3, Color3 } from "@babylonjs/core";

const SpinningBox = (props) => {
  const boxRef = useRef(null);

  return (
    <box
      name={props.name}
      ref={boxRef}
      size={2}
      position={props.position}
      height={1}
      width={0.75}
      depth={0.25}
    ></box>
  );
};

export const SceneWithSpinningBoxes = () => (
  <div>
    <Engine antialias adaptToDeviceRatio canvasId="babylonJS">
      <Scene>
        <arcRotateCamera
          name="camera1"
          target={Vector3.Zero()}
          alpha={(3 * Math.PI) / 4}
          beta={Math.PI / 4}
          radius={2}
        />
        <hemisphericLight
          name="light1"
          intensity={0.7}
          direction={Vector3.Up()}
        />
        <SpinningBox
          name="left"
          position={new Vector3(0, 0, 0)}
          color={Color3.FromHexString("#EEB5EB")}
        />
      </Scene>
    </Engine>
  </div>
);

export default SceneWithSpinningBoxes;

**Comment by crossLineApex** [comment]
I'm using React along with react-babylonjs, @babylonjs/core and @babylonjs/gui. My main task is to pass a url to a component and mesh it to a cuboid. Now I was just focusing on getting a cuboid which I'm able to do in the below code link. How should I go around and mesh an url image which I may get from a prop. For now you can use any image url without using any props and mesh it to the cuboid.

You can check my codesandbox here : https://codesandbox.io/s/divine-silence-ek9p5

**Comment by brianzinn** [comment]
@crossLineApex  To your cuboid you need to add a `material` and a `texture` to have the image show on the mesh.  The material will be assigned automatically to the mesh, if it's a direct descendant in the tree graph.  The texture you will want to assign using `assignTo` prop (same as the Skybox link above).

If you are using the Skybox then you can pass in different URLs:
https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/Basic/skybox.stories.js

If you are using screenshot utilities then there is a callback with data:
https://doc.babylonjs.com/divingDeeper/scene/renderToPNG#callback-function

Then from the callback to set the texture data you will need to create a new texture and that's easiest done using `key` prop. So, in your callback you will need to do something like use a counter to set the `key` (that is also in the Skybox code linked above).  The babylon doc example screenshot places the picture of the cube on the cube!

**Comment by brianzinn** [comment]
Pass in `faceUV` and `wrap` props when you create your box - here is a working fork:
https://codesandbox.io/s/festive-torvalds-ejprz
![image](https://user-images.githubusercontent.com/542756/116126740-d7676d80-a67b-11eb-9232-9584538de6c0.png)

**Comment by crossLineApex** [comment]
Thanks man. You were a great help. I'm able to understand the code now

**Comment by crossLineApex** [comment]
One last doubt here. How should I send url as a prop to the SpinningBox component ?

**Comment by brianzinn** [comment]
```jsx
const box = (props) =>
    <box
      ...
      faceUV={faceUV}
      wrap
    >
      <standardMaterial>
        <texture key={props.url} url={props.url} assignTo={"diffuseTexture"} />
      </standardMaterial>
    </box>
```

**Comment by crossLineApex** [comment]
But I'm rendering the SceneWithSpinningBoxes component and SpinningBox is a part of SceneWithSpinningBoxes. Do you have any suggestion for that ?

**Comment by brianzinn** [comment]
You can always pass it from your `index.js` and use prop drilling - at some place you would need to introduce the property.  If you are using state management then you can introduce the URL there.  `SpinningBox` *is* part of `SceneWithSpinningBoxes`, so maybe you meant something else?  I would avoid sending it from the app entry point (index.js) and look for a way with components.  Otherwise feel free to send through an updated sandbox that makes your issue more clear.

**Comment by crossLineApex** [comment]
I'll try to find a solution myself without disturbing you now!! If anything pops up will let you know

**Comment by brianzinn** [comment]
I don't mind at all - please re-open if you have any questions 😄
