### ISSUE TITLE
useAssetManager disposeInstanceOnUmount

### ISSUE THREAD

**Issue by dennemark** [brianzinn/react-babylonjs#129]
Hey,

I seem to be running into an issue when using useAssetManager.
Assume I have a 3d model at a specific url, that I would like to load/unload multiple times. I use useAssetManager to cache the 3D model and insert it into my react component via:

```
const MyComp = (urlToModel, children)=>{
  const assetManagerResult = useAssetManager([{ taskType: TaskType.Mesh, rootUrl: "", sceneFilename: urlToModel, name: urlToModel }], {reportProgress: true})

return <transformNode name={props.name}>
      {task.loadedMeshes && task.loadedMeshes.filter(m => m.name==="__root__").map((m,i)=>{       
        return <mesh name={m.name} 
          fromInstance={m} 
          key={i}         
          disposeInstanceOnUnmount>
          </mesh>
    })}
    {children}
    </transformNode>
}
```
1. Now i.e. I create `<MyComp urlToModel="/my/path" />`, the model gets loaded. 
2. Afterwards I unmount MyComp for whatever reasons.
3. At a later point I create a new component with the same path: `<MyComp urlToModel="/my/path" />`
-> In this case the model seems to load from cache, but it has the property `_isDisposed = true`. If I do not use `disposeInstanceOnUnmount` the model is visible, even if I unmount MyComp. 

Now I am wondering how I should handle this case.
I could enable/disable the asset on unmount, avoiding dispose. But the asset would stay in memory, probably until I dismount the whole scene. This is probably not good for garbage collection, if the amount of 3d models increases?

```
 useLayoutEffect(()=>{
  task.loadedMeshes.find(m => m.name === "__root__").setEnabled(true);
  return ()=>{
    task.loadedMeshes.find(m => m.name === "__root__").setEnabled(false);
  }
 },[])
```

**Comment by brianzinn** [comment]
I was waiting for somebody to come up with this one!  It's to do with how the promise needs to be cached (for fallback), but mainly due to how BabylonJS handles meshes in a scene that we are caching something attached to a scene instead of something we can "add" to a scene (like a basic geometry).  Perhaps in the unmount once the model is loaded the cache used could be cleared.  Let me think about that - what you have listed there will create memory pressure as you noted.  I suspect if we force reload that the browser may have cached the assets (or at least that is configurable on your side).

**Comment by dennemark** [comment]
Hi,
yes I am reusing the model without changes. And I agree the way Babylon handles geometry makes this issue a bit more complicated.
Is the above mentioned useEffect similar to just using another name/key for the task? It would lead to a complete redownload of the model (yes maybe from local cache) and initialize it again. I assume useAsset (by pmndrs) would be probably similar.

I think having some kind of function to clear/dispose all unused assets would be nice somehow, but they probably would need to be flagged as such. If we would count the number of dirty flags, we could i.e. say after 50 unused models clear/dispose them. But it sounds a bit hacky..

Besides the worries about memory issues, I feel useAssetManager works pretty nice! I can switch models instantly :)

**Comment by brianzinn** [comment]
Having multiple models simultaneously is something I'd like to fix at the same time.  The problem is that the component itself is completely reloaded everytime, since a promise is thrown - so cannot pass in a unique ID or anything.  I'm a bit stuck to be honest on how to solve both problems at the same time.  From what I saw `useAsset` would have the same issue, which is why I didn't go with it originally.

**Comment by brianzinn** [comment]
@dennemark  Also, did you mean that you can switch models instantly with your code using `setEnabled`, but also that you don't load multiple of same model into your scene at the same time, right?

**Comment by dennemark** [comment]
@brianzinn yes I am switching via setEnabled. My react component is unmounted and as soon as I mount it again, I get my old asset via useAssetManager and set enabled to true. This works very well. I guess if I do not alter the model, I could probably even use multiple components, since I use <mesh fromInstance={myAsset} ...  

Concerning having multiple models simultaneously, I am wondering if you are referring to the useAssetModel? What does it mean exactly? I guess useAssetManager can run multiple tasks, but the issue is to load the same model twice without using instances? I haven't tried it yet, but using different task names for same url does not work?

**Comment by dennemark** [comment]
Since this issue is a bit older: so far my approach of enabling and disabling meshes worked out well so far. Also using different key names for assets i.e. from the same url, works well.

But now Istumbled over a case where I would load multiple assets quite fast. Lets say I have 10 models to load and switch through them fast. My component using useAssetManager is called each time I choose a model. So useAssetManager will load the model on mount. However unmounting the component, the model will be disabled. - Thats the base case that we already solved within this issue. But it has side effects, when the component is unmounted before useAssetManager finishes the model loading task.
Normally the model is disabled on unmount, but since it does not exist yet on unmount, I cannot hide it. So switching through 10 models rapidly, they might appear all at once.

I wanted to solve this issue by using the onSuccess callback of MeshAssetTask - however it seems the task of useAssetManager does not contain this callback. I checked the useAssetManager hook and it seems the actual underlying task is created here: https://github.com/brianzinn/react-babylonjs/blob/34cfc0adce03ace62cc3cbb0ec2fa8ec66799e4e/packages/react-babylonjs/src/hooks/loaders/useAssetManager.tsx#L195

But i cannot find a location where it is exposed. And the taskMap that is returned at the end says, it is a AbstractAssetTask, but as far as I can see, it is mainly the Task Type
https://github.com/brianzinn/react-babylonjs/blob/34cfc0adce03ace62cc3cbb0ec2fa8ec66799e4e/packages/react-babylonjs/src/hooks/loaders/useAssetManager.tsx#L206

Is it somehow possible to expose the underlying task to call onSuccess on it?

**Comment by dennemark** [comment]
Tested the approach. It seems to work.

I am sometimes using react-query, which is pretty nice. However, I would expect a similar outcome. React-query is not cancelling the fetch on unmount, except one does it manually. So the loaded asset would still be processed by babylonjs. It would need this onSuccess callback, too. I guess.

**Comment by brianzinn** [comment]
Thanks for the PR - it adds a good extension point - I think you also need to remove from the cache manually.  SceneLoader does so when you call dispose on the results - how are you handling that in your race condition?
https://github.com/brianzinn/react-babylonjs/blob/master/packages/react-babylonjs/src/hooks/loaders/useSceneLoader.tsx#L226

**Comment by dennemark** [comment]
I haven´t thought about this yet. I guess I never disposed my meshes yet when using useAssetManager :D
So if I understood it correctly, useAssetManager currently does not handle disposal of loaded assets. If I would dispose the asset for example with `<mesh ... disposeOnUnmount/>` the cache of useAssetManager does not know about it, right?

Did you want to achieve this with  ` return () => clearSuspenseCache(key); ` It seems to be quite good, I guess. I am wondering if the clearing function could include the disposal, too. But maybe it is nicer to just have some HOC that is using these functions internally.

**Comment by dennemark** [comment]
I have a component i.e. that is using useAssetManager internally and allows to turn on render overlay / outline / shadows and wraps around a normal `<mesh />` component. For this component I could just use `return () => clearSuspenseCache(key);` in the unmount function if i wanted to. So others could easily use the component without thinking about the complexities of the asset manager. But thinking about it, it would still be nicer to have just a simple hook that one can deal with.

**Comment by brianzinn** [comment]
Let me make it public. I could also change the return signature (like useState)…. do you think one way is better?

**Comment by brianzinn** [comment]
I'm closing from inactivity - I think this is fixed in newer versions.  Kindly re-open if this is a missing feature.
