### ISSUE TITLE
Unable to run the storybook locally

### ISSUE THREAD

**Issue by shaderstack** [brianzinn/react-babylonjs#133]
I'm trying to run `npm run storybook`. Getting this error currently on my ubuntu machine - 

```
ERR! Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/absi/ss/react-babylonjs/.storybook/main.js
ERR! require() of ES modules is not supported.
```

Let me know if more info is needed to debug this.

**Comment by brianzinn** [comment]
Hi, sorry you ran into that one. It’s a pain. The “type: module” needs to be removed from storybook. I keep intending to move storybook into a sub folder completely - not just to fix that, but to clean the dependencies as well. I think I can get to that next month, finally...

**Comment by shaderstack** [comment]
Cool, thanks. Closing this.
