### ISSUE TITLE
Support for multiple views rendering multiple scenes

### ISSUE THREAD

**Issue by Sewdn** [brianzinn/react-babylonjs#136]
Hi @brianzinn !

Is there any support to use multiple canvases rendering multiple scenes:
- https://doc.babylonjs.com/divingDeeper/scene/multiCanvas
- https://doc.babylonjs.com/divingDeeper/scene/multiScenes

The goal is to build an app that allows for:
- using a default scene with a free camera to move around a scene and select objects
- when object is selected, show UI controls to show details
- when detail is shown, display an overlaying canvas, rendering another scene (with a highpoly model of the selected model) using a ArcRotateCamera to rotate object around + zoom in/out
- close detail (overlay); unregister view, attach control back to default canvas with loaded scene

First 2 goals are ok.

I'm now trying to accomplish the other requirements, but I cant seem to find any declarative approach for registering views. I therefor switched back to a procedural approach in the overlay components.
But as soon as I am rendering another canvas in overlay, my canvas in the background switches to the newly created scene.
Is this because the default (free)camera was not attached to a view?

Help would be much appreciated in how to accomplish these requirements (working as declarative as possible).

Thanks!

Kind Regards,
Pieter

**Comment by brianzinn** [comment]
Hi @Sewdn - I would like to support that scenario.  The underlying reason that the Engine and Scene components were separated was to allow multi-scene functionality.  We will need to add a way to control the render loop based on activeView.  Are you able to share the procedural approach you have used and then we can look at a declarative solution?

**Comment by Sewdn** [comment]
Multiple scenes for the same canvas with the same canvas, shouldnt be a problem with the current approach. There should currently be a declarative support for using multiple Scenes withing the same Engine(Provider), for:
- rendering multiple scenes at once on the same canvas: https://playground.babylonjs.com/#L0IMUD#1
- rendering multiple scenes in sequence on the same canvas https://playground.babylonjs.com/#MXCRPS#1

by controlling the renderLoop of the engine (this should be possible, by using useEngine, stop the current loop and start a new one.

However, using multiple canvases is currently not possible in my experience. I think the root of the problem is that, currently, Engine is tight to the canvas it generates (https://github.com/brianzinn/react-babylonjs/blob/eb7e4dfaa9f9a8a03df18212c79a463ba20cf9cf/src/Engine.tsx#L145).

When trying to use mukltiple canvases, this main or default canvas shouldn't be used to draw the main scene (apparently, using this example; https://github.com/BabylonJS/Website/blob/master/build/Demos/Views/index.html). Instead, we should resort to creating a separate canvas per View in order to simultaneneously render multiple cameras for the same scene or different scenes on multiple canvases.

To support this, I believe the API for the Camera component should be expanded with an optional prop of a canvas reference (an id: string, or a ref: HTMLCanvasElement). As soon as this prop is provided the Camera component component should register a new view with the engine of the  scene it was attached to.

I'll thinker around with these new insights and maybe provide you with a storybook setup with a procedural approach for this scenario, inside a declarative tree with Engine and Scene components.

**Comment by brianzinn** [comment]
There is a recent ongoing discussion (https://github.com/brianzinn/react-babylonjs/discussions/130) and I hope to unify `engine.registerView(...)` and `camera.viewport`.  We can also consider custom host elements like `<viewport>` or `<view>` that could be understood by the reconciler (ie: when a camera is created we can walk up the treegraph) then the canvas could be perhaps a prop of the viewport.  I'm just thinking out loud to provide other potential declarative options.

**Comment by brianzinn** [comment]
There's an EngineView created on `engine.registerView(...)` (https://doc.babylonjs.com/typedoc/classes/babylon.engine#registerview).  My proposal is then to support that declaratively.  The registerView method has 2 parameters: canvas and optional camera.  I am still working out a simple way to attach a camera that makes sense declaratively (there is also a `target` property on the EngineView (https://doc.babylonjs.com/typedoc/classes/babylon.engineview) itself).
```jsx
<Engine noCanvas={true}>
  <Scene ...>
    <engineView canvas={canvasRef} camera={???} >
       <arcRotateCamera ... />
    </engineView>
    <engineView canvas={canvasRef2} camera={???} >
       <freeCamera ... />
    </engineView>
  </Scene>
  <Scene ...>
    <engineView canvas={canvasRef3} camera={???} >
       <arcRotateCamera ... />
    </engineView>
  </Scene>
</Engine>
```
I will call `engine.registerView()` automatically and I could get the camera perhaps automatically from the scene graph.

This then raises a question about how to control the render loop for the engine and active view (with multiple scenes).  Maybe if you could share your declarative code we can work between these 2 ideas to a solution?

**Comment by Sewdn** [comment]
Thanks for your swift responses and action!

I'll invest more time in this next week. Short feedback on your proposal:
We need developer-friendly support for 4 different use cases:

- [x] 1. one scene on one canvas
- [x] 2. multiple scenes on one canvas
- [ ] 3. one scene on multiple canvases
- [ ] 4. multiple scenes on multiple canvases

I think your proposal allows for completeness of 3. and 4.

3.
```
<Engine noCanvas={true}>
  <Scene ...>
    <engineView canvas={canvasRef} camera={???} >
       <arcRotateCamera ... />
    </engineView>
    <engineView canvas={canvasRef2} camera={???} >
       <freeCamera ... />
    </engineView>
  </Scene>
  </Engine>
```

4.
```
<Engine noCanvas={true}>
  <Scene ...>
    <engineView canvas={canvasRef} camera={???} >
       <arcRotateCamera ... />
    </engineView>
  </Scene>
  <Scene ...>
    <engineView canvas={canvasRef3} camera={???} >
       <arcRotateCamera ... />
    </engineView>
  </Scene>
</Engine>
```

Nice!

However, I would expect the engineView to be an optional child of the camera, since you need an optional camera instance when creating the view? Every camera component should setup a camera provider then, to access it from context?

```
<Engine noCanvas={true}>
  <Scene ...>
       <arcRotateCamera ... >
           <engineView canvas={canvasRef} />
        </arcRotateCamera>
  </Scene>
</Engine>
```

Or you setup more loose coupling and provide a cameraRef tot the engineView as an optional prop?

```
<Engine noCanvas={true}>
  <Scene ...>
       <arcRotateCamera ref={cameraRef} ... />
       <engineView canvas={canvasRef} camera={cameraRef.current} />
  </Scene>
</Engine>
```
I think  this last approach, feels most natural, as the use of engineViews related to camera is optional and shouldnt be impacted on how t setup cameras in the scene?
Actually, the engineview is not directly related to the scene, and could therefor be moved outside of the Scene scope?

3) would look like this

```
<Engine noCanvas={true}>
  <Scene ...>
       <arcRotateCamera ref={cameraRef} ... />
       <freeCamera ref={cameraRef2} ... />
  </Scene>
  <engineView canvas={canvasRef} camera={cameraRef.current} />
  <engineView canvas={canvasRef2} camera={cameraRef2.current} />
</Engine>
```


4) would look like this

```
<Engine noCanvas={true}>
  <Scene ...>
       <arcRotateCamera ref={cameraRef1} ... />
  </Scene>
  <Scene ...>
       <arcRotateCamera ref={cameraRef2} ... />
  </Scene>
  <engineView canvas={canvasRef} camera={cameraRef.current} />
  <engineView canvas={canvasRef2} camera={cameraRef2.current} />
</Engine>
```

But this setup would allow to switch easily from scene or camera from existing canvases (in declarative way)

**Comment by Sewdn** [comment]
The complex part wouldnt be registering the views dynamically, but rather unregistering them, when they are destructed. My first experiments are not succeeding in correctly cleaning them up (even not procedurally).

The other complex part would be in setting op a generic renderLoop function that renders only the scenes, that have at least one activeCamera that was registered with an engineView.

**Comment by brianzinn** [comment]
hi @Sewdn - sorry taking so long.  Been extremely busy lately.  I am able to do this right now:

```jsx
const MultiCanvas = ({secondCanvas}) => {
  const freeCameraRef = useRef(undefined);
  return (
    <>
      <BoxWithArrows position={Vector3.Zero()} />

      <hemisphericLight name='light1' intensity={0.7} direction={Vector3.Up()} />

      <freeCamera name='freeCamera' ref={freeCameraRef} position={new Vector3(0, 5, -10)} setTarget={[Vector3.Zero()]} setActiveOnSceneIfNoneActive={false} />

      <arcRotateCamera name='camera1' alpha={3 * Math.PI / 8} beta={3 * Math.PI / 8} radius={15} target={new Vector3(0, 2, 0)} />

      {(secondCanvas && secondCanvas.current !== null) &&
        <engineView canvas={secondCanvas.current} camera={freeCameraRef.current} />
      }
    </>
  )
}

export const EngineView = () => {
  const secondCanvasRef = useRef(null);
  return (
    <div className="container">
      <div className="box">
        <Engine antialias adaptToDeviceRatio canvasId='babylonJS'>
          <Scene clearColor={new Color3( .5, .5, .5)}>
            <MultiCanvas secondCanvas={secondCanvasRef} />
          </Scene>
        </Engine>
      </div>
      <div className="box">
        <canvas className='second-canvas-babylon' ref={secondCanvasRef} />
      </div>
    </div>
  );
}
```
I'll try to add proper declarative support as indicated above and also verify the multi-scene functionality.  I haven't published to NPM yet, but if you were keen you could build locally and run storybook to see it working.

**Comment by brianzinn** [comment]
Also, these engine views should `unRegisterView` automatically, but may need to store a canvas reference compared to how it is being done currently.

**Comment by brianzinn** [comment]
closing for housekeeping purposes - please re-open if not solved.
