### ISSUE TITLE
Missing equivalent of onPointerOverTrigger() in source code

### ISSUE THREAD

**Issue by skaraen** [brianzinn/react-babylonjs#14]
I want to trigger an event when my cursor hovers over a 3D model...but I can't the equivalent of **onPointerOverTrigger()** which is present in babylonjs.

**Comment by brianzinn** [comment]
Do you mean an ActionManager for a mesh?  A model can have multiple meshes, so maybe the onModelLoaded() will work for you to get that reference?  Let me know and I will update the example repo.

**Comment by siliconCupcake** [comment]
So, if I were to use the ActionManager, how would I obtain the reference to the current scene ?

**Comment by brianzinn** [comment]
hi @siliconCupcake,  There are a couple of ways to get the scene reference.  Depends on your design.  If you wanted to build everything into a single page, you would probably do something like:
```jsx
import { ..., ActionManager, SetValueAction } from 'babylonjs';

let myScene = null;
class WithModel extends Component 
{
  onModelLoaded(model) {
    let mesh = model.meshes[1];
    mesh.actionManager = new ActionManager(myScene);
    mesh.actionManager.registerAction(
      new SetValueAction(
          ActionManager.OnPointerOverTrigger,
          mesh.material,
          'wireframe',
          true
      )
    )
    mesh.actionManager.registerAction(
      new SetValueAction(
          ActionManager.OnPointerOutTrigger,
          mesh.material,
          'wireframe',
          false
      )
    )
  }

  render() {
    return (
      <div>
         <Engine antialias={true} adaptToDeviceRatio={true} canvasId="sample-canvas">
              <Scene onSceneMount={(e) => {
                myScene = e.scene
              }}>
                <Model .... onModelLoaded={this.onModelLoaded} />
            </Scene>
          </Engine>
      </div>
    )
  }
}
```

So, the other way and the way I would do it would be to write a Component and use the HOC with Scene, so the scene will be passed using the React Context API.  You could, for example, export your component as:
```jsx
export default withScene(ScaledModelWithProgress)
```
Then within that component, you will get added to your props a sceneContext (this.props.sceneContext), which has Scene, Engine and Canvas, which you can directly use.

**Comment by skaraen** [comment]
@brianzinn Thanks ! That did the trick !!

**Comment by brianzinn** [comment]
I added to demo site how to do it with a Component using the withScene() HOC - you can PointerOver the boombox to see:
https://brianzinn.github.io/create-react-app-babylonjs/withModel
