### ISSUE TITLE
Get clicked point on the model - React Babylon JS

### ISSUE THREAD

**Issue by SurajMK94** [brianzinn/react-babylonjs#153]
Hi team,

How can i get the vector3 coordinate of the mouse clicked point on the 3D model in React Babylon JS code?

Thanks and Regards,
Suraj M K

**Comment by brianzinn** [comment]
here is a code sandbox:
https://codesandbox.io/s/quizzical-cache-8ytn4?file=/src/App.tsx
![pointer-down-vector](https://user-images.githubusercontent.com/542756/133949055-874def44-a3dc-4d67-9ebb-fa9bdd970e09.gif)

**Comment by brianzinn** [comment]
Please re-open if above solution does not work for you.

**Comment by SurajMK94** [comment]
Thank you for the solution Brian. It worked for me.
