### ISSUE TITLE
Input Text field for the UI - React Babylon JS

### ISSUE THREAD

**Issue by SurajMK94** [brianzinn/react-babylonjs#154]
Hi team,

Is there a way to click a UI element and type the text using keyboard and save it?

Thanks and Regards,
Suraj M K

**Comment by brianzinn** [comment]
https://codesandbox.io/s/snowy-voice-l1k3h?file=/src/App.tsx
![input-text-capture](https://user-images.githubusercontent.com/542756/133949919-be6729db-edf2-473a-b682-cdb063aa51aa.gif)

If you are using a declarative GUI then it's the observable on the `inputText` control.
```jsx
<inputText
    text="circle"
    color="white"
    fontSize={150}
    width={1.0}
    onTextChangedObservable={(ctl: InputText) =>
       console.log("new text:", ctl.text)
    }
 />
```

**Comment by brianzinn** [comment]
Please re-open if above solution does not work for you.

**Comment by SurajMK94** [comment]
Thanks alot Brian. This solution worked like a magic.
