### ISSUE TITLE
How to use the default rendering pipeline

### ISSUE THREAD

**Issue by stoikerty** [brianzinn/react-babylonjs#17]
Hey brianzinn,

I've been using react-babylonjs for a while and I have generally always figured out how to do what I needed with `react-babylonjs`. I've figured out how to use materials, the non-declarative mode as well as make it work with [`react-spring`](https://github.com/react-spring/react-spring) (so far an excellent combo).

However I have just come across [the rendering pipeline](https://doc.babylonjs.com/how_to/using_default_rendering_pipeline) which allows for motion blur as well as depth of field effects and I'm not sure how I would use it with `react-babylonjs`.

Do you have an example or snippet where the rendering pipeline is used?

**Comment by brianzinn** [comment]
let me try to set one up this weekend.  i'll setup a depth-of-field one using non-declarative and if you need a declarative we can look into it more.

**Comment by stoikerty** [comment]
That's super helpful, thank you! 😃 

Been reading your PR's. There's certainly a collaborative passion-project going on here!

**Comment by brianzinn** [comment]
Yeah, it went from a thought project to somewhat more time consuming that I had anticipated :) Just checked out react-spring - looks really interesting.  I'm going to check it out more.

What I did was to update the example in `create-react-app-babyonjs` with just a copy of the Depth of Field playground. Is something like this going to work for you?
Demo: https://brianzinn.github.io/create-react-app-babylonjs/nonDeclarative
Source: https://github.com/brianzinn/create-react-app-babylonjs/blob/master/src/nonDeclarative.js

**Comment by stoikerty** [comment]
Thanks for taking the time to make that example, really appreciate it! I understand it a bit better now. You basically do everything inside `onSceneMount`. It's funny how there is still quite a strong split between declarative and non-declarative for a lot of things.

Everything that's declarative is very intuitive but what falls outside of it becomes awkward to use in many ways if you're used to doing react-applications. Passing `scene` and `canvas` to sub-components is doable but seems quite tricky. I'll be experimenting some more. I might make a wrapper around `<Scene>` to pass some exclusive properties down as render-props.

**Comment by brianzinn** [comment]
You don't need to pass `scene` and `canvas` to sub-components - there is a High Order Component (HOC) `withBabylonJS` that will include the `props.sceneContext` containing both, so you don't need to "drill props".

Here are examples (note the export at bottom):
- https://github.com/brianzinn/create-react-app-babylonjs/blob/master/src/SingleAxisRotateMeshBehavior.js

- https://github.com/brianzinn/create-react-app-babylonjs/blob/master/src/ScaledModelWithProgress.js
