### ISSUE TITLE
camera target not work

### ISSUE THREAD

**Issue by stanleySHU** [brianzinn/react-babylonjs#170]
camera target not work.  version: 4.2.0
<freeCamera name="camera" position={new Vector3(0, 1000, 0)} target={new Vector3(0, 0, 0)}/>

**Comment by brianzinn** [comment]
hi @stanleySHU - I think the target does work, but the thing about the reconciler is that the position and target and setting them produces unexpected behaviour.  Look here as an example:
https://www.babylonjs-playground.com/#6P3E3K

![image](https://user-images.githubusercontent.com/542756/139506950-c91c665b-245b-4030-bb71-2fa6e56b7a2e.png)
What happens is that when the position changes that the target changes by the same amount.

You maybe want to use `lockedTarget` and I just checked and that property is indeed not supported, but if that is what you are after then I could add it.

**Comment by brianzinn** [comment]
sorry, but I didn't mean to close actually.  Please re-open if it's not solved for you.
