### ISSUE TITLE
.mtl files for custom made models not getting cached even after writing manifest files.

### ISSUE THREAD

**Issue by sriram1998** [brianzinn/react-babylonjs#18]
Included a manifest file for every .obj files and .mtl files which has the following json:
{
  "version" : 1,
  "enableSceneOffline" : true,
  "enableTexturesOffline" : true
}
.obj files are getting cached but not .mtl files

**Comment by brianzinn** [comment]
.mtl caching can be added.  Can you put this as a feature request/bug in the main forum (https://forum.babylonjs.com/)?

I have added the recent feature requests on OBJ file loader for `babylonjs`, so can pick it up there.

**Comment by sriram1998** [comment]
I have opened a new topic in the forum. Thank you.

**Comment by brianzinn** [comment]
cool.  another option as well that will work for all resources is a progressive web app.  the service worker will serve everything offline (your whole game/website will work offline).  i have a demo here:
https://github.com/brianzinn/create-react-app-babylonjs-pwa

**Comment by sriram1998** [comment]
Will check it out. Thank you.

**Comment by brianzinn** [comment]
I'm going to close as it's something that babylonjs should support, although would expect the browser to cache textures :)
