### ISSUE TITLE
Cannot run the SpinningBox Example

### ISSUE THREAD

**Issue by weypro** [brianzinn/react-babylonjs#183]
Hi. I created a new react project
```
npx create-react-app spinningbox
```
 and added babylonjs with the command:
```
yarn add react-babylonjs @babylonjs/core @babylonjs/gui
```
After initializing the project, I tried to run the SpinningBox Example and make some changes:
1. Before:`export  const  SceneWithSpinningBoxes  =  ( )  =>  ( `
After:`const SceneWithSpinningBoxes = () => (`
2. Before (the template):
```
function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </header>
    </div>
  );
}
```
After:
```
function App() {
  return (
    <div className="App">
      <SceneWithSpinningBoxes>
      </SceneWithSpinningBoxes>
    </div>
  );
}
```
The code was compiled successfully, but nothing displayed on the page.

**Comment by brianzinn** [comment]
hi @weypro - Have a look here.  You don't need to export SceneWithSpinningBoxes unless it's in a different file.
https://codesandbox.io/s/epic-darwin-tohk0?file=/src/App.tsx

**Comment by weypro** [comment]
Yes, I think exporting `SceneWithSpinningBoxes` doesn't affect the result. Actually, I find the truth that  the canvas size must be defined like this:
```
#babylon-canvas {
  width: 80%;
  height: 80%;
}
```
Otherwise the size may be 'infinite' and make the WebGL engine crash.
By the way, the canvas id is `babylonJS` in the JSX example in `README.md` while it's `babylon-canvas` in the TSX example. I think it's better to use the same id.
