### ISSUE TITLE
Set hostInstance.parent for child of Camera?

### ISSUE THREAD

**Issue by Bkucera** [brianzinn/react-babylonjs#19]
I guess this is more of a question,

Whats the best way to set a mesh's parent to a Camera? 

Could a camera property be added to automatically set parent/children on the hostInstance?

With this code:
```js
<FreeCamera
...

/>
  <Box .../>
</FreeCamera>

```

The `Box` will not have its position local to the camera.

**Comment by brianzinn** [comment]
I think the default behaviour should be that your snippet would work. I have to look at inheritance hierarchy to see why it isn't working for you. When you parent to a FreeCamera - what are you trying to build?

Parenting is currently handled here: https://github.com/brianzinn/react-babylonjs/blob/master/src/customComponents/MeshLifecycleListener.ts - I need to check if I should hook these up lower in class hierarchy like `node`...

**Comment by Bkucera** [comment]
@brianzinn since camera doesn't have `isMesh` set in `metadata`, the mesh lifecycle listener is not applied, it gets the CameraLifecycle listener

I'm just trying to parent a mesh to a camera so that a player can control a camera, which ends up moving a Mesh

**Comment by saidmoya12** [comment]
For best practices use TransformNode instance mesh transform.

```jsx
<TransformNode position={new Vector3(x,y,z)} ...>
  <FreeCamera ...  />
  <Box .../>
<TransformNode>
```

[TransformNode stories](https://github.com/brianzinn/react-babylonjs/blob/d39739635d1f4a114e39d8d16ef1c66b921792ba/stories/babylonjs/Basic/transformNode.stories.js)

[Use TransformNode](https://doc.babylonjs.com/how_to/optimizing_your_scene#use-transformnode-instead-of-abstractmesh-or-empty-meshes)

**Comment by brianzinn** [comment]
Definitely when this issue was created it was not possible.  I think there are multiple ways to do this now using either a `<TransformNode .../>` from previous comment or from the above commit that allows non-meshes to automatically parent each other based on declaration.  Please re-open if there is something not possible or unclear.
