### ISSUE TITLE
how to use VirtualJoystick

### ISSUE THREAD

**Issue by GzxNydia** [brianzinn/react-babylonjs#208]

**Comment by brianzinn** [comment]
hi Nydia,

I do not have a component for this.  You will need to do so imperatively. Like:
```
const leftJoystick = new VirtualJoystick(true);
const rightJoystick = new VirtualJoystick(false);
...
```

If you can present a case for needing declarative then I will look at adding.

**Comment by brianzinn** [comment]
Please re-open if you would like declarative support added.
