### ISSUE TITLE
Loaded Model merge meshes

### ISSUE THREAD

**Issue by dottodot** [brianzinn/react-babylonjs#216]
I'm trying to merge meshes on a loaded model but it always returns `null` and I'm not sure if it's react-babylonjs issue or not. 

I'm using this https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Box/glTF-Binary/Box.glb and implementing as follows.

```
function BoxModel() {
  const onModelLoaded = ({meshes}) => {
    const merged = Mesh.MergeMeshes(meshes);
    console.log(merged);
  };

  return (
    <Suspense fallback={null}>
      <Model
        rootUrl={`models/`}
        sceneFilename="Box.glb"
        scaleToDimension={3}
        position={new Vector3(0, -2, 0)}
        onModelLoaded={onModelLoaded}
      />
    </Suspense>
  );
}
```

If I use a mesh created using MeshBuilder it works as expected.

```
MeshBuilder.CreateSphere("sphere1", {diameter: 2, segments: 16}, scene);
```

**Comment by brianzinn** [comment]
I've never used MergeMeshes, but it looks like it ought to work - was just reading the docs here:
https://doc.babylonjs.com/divingDeeper/mesh/mergeMeshes

One thing that I do is parent to a rootmesh in the Component, so this may work:
```
const onModelLoaded = ({rootMesh}) => {
    const merged = Mesh.MergeMeshes([rootMesh]);
    console.log(merged);
  };
```

I would probably drop down to the hook itself as likely you want to dispose the original meshes (2nd parameter).  The component is here - it's mainly a wrapper that calls a hook and disposes the model on component unmount:
https://github.com/brianzinn/react-babylonjs/blob/master/packages/react-babylonjs/src/customComponents/Model.tsx

Are you able to share a code sandbox otherswise?

**Comment by brianzinn** [comment]
Closing from inactivity and no reply - I am unable to reproduce locally.  Please re-open if you have more feedback - thank you.
