### ISSUE TITLE
Strongly typed ref in BabylonNode<T>

### ISSUE THREAD

**Issue by coder89** [brianzinn/react-babylonjs#218]
Currently `BabylonNode<T>` declares `ref` as `Ref<ReactNode>`. Therefore we need to write something like this:
```jsx
const ref = useRef();
useEffect(() => {
  const mesh = ref.current as Mesh;
}, []);
return <mesh ref={ref} />
```

`generatedProps.d.ts` should be updated to allow below:
```jsx
const ref = useRef<Mesh>();
useEffect(() => {
  const mesh = ref.current;
}, []);
return <mesh ref={ref} />
```

I have created a PR that fixes the issue: #217

**Comment by brianzinn** [comment]
Thanks. I’ll merge in tonight. Appreciate the PR!
