### ISSUE TITLE
React Hooks full support

### ISSUE THREAD

**Issue by fselcukcan** [brianzinn/react-babylonjs#23]
Will react Hooks be supported fully, including for adding observables?

**Comment by brianzinn** [comment]
Are you changing an observable at run-time?  I'd be interested to see a good use case.  I can add support - it would require me to track the old observable and remove/reattach - not sure if that's going to open up some race conditions.

**Comment by brianzinn** [comment]
I've added observable support with hooks at Scene level here (any other Scene observables can be done in same way):
https://github.com/brianzinn/react-babylonjs/blob/master/src/hooks.ts#L8

With `useEffect` it is automatically unregistered.  I'm still thinking about adding generically to components, if there is a valid declarative use-case.  Can you provide a use-case where you need it at non-scene/engine level?

**Comment by seed-of-apricot** [comment]
Could you please publish a new version to npm so that we can use the new feature? Or aren't you decided to go with the approach yet?

**Comment by brianzinn** [comment]
@seed-of-apricot I was planning to do more testing, as there were bigger changes to Scene component, but looks good in storyboard, so published 2.0.2 :)
