### ISSUE TITLE
HTML Distance Factor - Lock Certain Axis

### ISSUE THREAD

**Issue by DenysAshikhin** [brianzinn/react-babylonjs#232]
Hi,

First of, just wanted to say that this library is great and genuinely a joy to use (learning curve of being new to babylon and web 3d graphics aside of course).

I am using the HTML element and having issues with it being positioned how I want. The closest I figured out was playing with the distance_factor, however, it shifts the element up/down (relative to camera view port?) and stretches/shrinks the element. Is there a way to just have it not affect the placement of the element as I zoom in/out?

The scaling is fine, I can work with that, but the offset is the issue. 

Thanks!

Demo: https://youtu.be/CMbx-1_Ts30

**Comment by brianzinn** [comment]
Thanks @DenysAshikhin - That is a good question and I think I understand from the linked video how you want the Html component to behave.  Are you able to share a reproduction in code?

cc @dennemark

**Comment by dennemark** [comment]
Hi @DenysAshikhin I think you just need to remove distanceFactor, then it should work already. Or am I missing something?

**Comment by DenysAshikhin** [comment]
So not quite, the way I have it now, is I use a (normally invisible and tiny, but for demo purposes I made it white and big, which is overlayed on the person model. This serves as the anchor for the HTML element. However, when I zoom out the HTML element is way off from the actual model it's anchored too, but zoomed in it's okay.

Screenshots to show issue better: 
![Screenshot 2022-07-28 081756](https://user-images.githubusercontent.com/10791321/181503562-3a640f86-22bb-49a1-ae91-89b755aa6706.png)
![Screenshot 2022-07-28 081824](https://user-images.githubusercontent.com/10791321/181503564-7c33d4fc-8782-4658-892f-8f66a26a380f.png)


This is why no distance-factory set at all.

@brianzinn is there a sandbox somewhere I can code in an example with react and babylon-react already setup? If so I can do it there, or would you prefer like a single .js file to plug in?

**Comment by brianzinn** [comment]
Yes - usually for issues to use code sandbox - ie:
https://codesandbox.io/embed/magical-elgamal-hg02q0?codemirror=1

otherwise to fork this repo and use the storybook or website, but that is usually for library changes/fixes.

**Comment by DenysAshikhin** [comment]
> Yes - usually for issues to use code sandbox - ie: https://codesandbox.io/embed/magical-elgamal-hg02q0?codemirror=1
> 
> otherwise to fork this repo and use the storybook or website, but that is usually for library changes/fixes.

I just added the Html in there, if you zoom out, you can see the div just goes wayyy of from the actual box it is linked to:
https://codesandbox.io/s/great-fast-jo0klb?file=/src/App.tsx

**Comment by dennemark** [comment]
I see what you mean.
This happens for me too, if I turn on the inspector in my app.
I need to have a look at it next week. But my guess is, that it is related to the reference div or canvas that is used to calculate the position of the html element.
To me it looks like, we get the relative position of the boxes on the canvas, but they are projected onto the parent div of the canvas.

**Comment by DenysAshikhin** [comment]
I'll keep an eye out here for any response/suggestion, but the expected (intuitively) interaction is the element stays the same size, and in the same place, and changing the distance_factor would change the scale/size (much how `transform: scale()` works based on camera zoom level?

Let me know if there is anything else I can do to help!

**Comment by dennemark** [comment]
I think I have it. Try position relative - makes sense for CSS.

```
<div style={{position:"relative"}}>
    <Engine antialias adaptToDeviceRatio canvasId="babylon-canvas">
      
```

Maybe we should include it in the examples with comment line.

**Comment by DenysAshikhin** [comment]
It's better, but issue still persists?

![image](https://user-images.githubusercontent.com/10791321/181533246-eea8f008-e0c3-4711-a55c-efa927c9adc5.png)
![image](https://user-images.githubusercontent.com/10791321/181533828-6fa240a0-8fde-455e-8fe0-c84b818fa28a.png)

**Comment by brianzinn** [comment]
You can pass-through styles as well on the Engine - they should be attached to the canvas.
I think it is:
```
<Engine style={{position:"relative"}}>
 ...
</Engine>
```

**Comment by DenysAshikhin** [comment]
> You can pass-through styles as well on the Engine - they should be attached to the canvas. I think it is:
> 
> ```
> <Engine style={{position:"relative"}}>
>  ...
> </Engine>
> ```

I feel like I'm missing something:
![image](https://user-images.githubusercontent.com/10791321/181598552-48d1ed73-8336-41b3-b289-4fc053c89942.png)
![image](https://user-images.githubusercontent.com/10791321/181598597-16f6ca89-3676-436a-bbf1-e8cd2384a05c.png)


It looks like it's keeping it in the same spot on the canvas? But that's not correct since as you zoom out, the distance from the box and the div still increases...

**Comment by brianzinn** [comment]
something is not working with the `style` on `<Engine... />` - I can look at that separately.  Definitely seeing the inspector mess things up though, so looks related.

**Comment by DenysAshikhin** [comment]
Sounds good, again, let me know if there's anything else I can do to help out/troubleshoot/test

**Comment by dennemark** [comment]
> > You can pass-through styles as well on the Engine - they should be attached to the canvas. I think it is:
> > ```
> > <Engine style={{position:"relative"}}>
> >  ...
> > </Engine>
> > ```
> 
> I feel like I'm missing something: ![image](https://user-images.githubusercontent.com/10791321/181598552-48d1ed73-8336-41b3-b289-4fc053c89942.png) ![image](https://user-images.githubusercontent.com/10791321/181598597-16f6ca89-3676-436a-bbf1-e8cd2384a05c.png)
> 
> It looks like it's keeping it in the same spot on the canvas? But that's not correct since as you zoom out, the distance from the box and the div still increases...

I think these issues happen, because of the #babylonScene css style with width and height at 80% in the style.css.

**Comment by DenysAshikhin** [comment]
Hey all,

That seems to have fixed the issue, I'll close this now, thanks for all your help!
