### ISSUE TITLE
react-reconciler dependency prevents upgrade to react 18

### ISSUE THREAD

**Issue by mike-at-hypothetic** [brianzinn/react-babylonjs#235]
I get the following conflict when upgrading to react 18:
`warning "react-babylonjs > react-reconciler@0.26.2" has incorrect peer dependency "react@^17.0.2".`

**Comment by brianzinn** [comment]
you're right - it should be `0.26.7`.  I'll try to get a fix out this weekend - should be a warning you can ignore as it's a peer dep.

**Comment by mike-at-hypothetic** [comment]
Thanks for the quick response!  No need to rush but I wanted to put it on your radar.

**Comment by brianzinn** [comment]
thanks @mike-at-hypothetic - i bumped everything up and should be good on `react-babylonjs@latest` version (3.1.7).  please re-open if not solved.  cheers.
