### ISSUE TITLE
Context lost in child components (Error with providers like Redux, React Router and Zustand)

### ISSUE THREAD

**Issue by saidmoya12** [brianzinn/react-babylonjs#236]
I would like to know if it is possible to keep the "context" in the child components of scene

Child components lose context within the scene, so I have problems with react router, redux or zustand hooks inside child components

I know it's a context issue, because I was able to fix react-routerV5 with the following code

```jsx
<Scene>
    <RouterContext.Provider value={router}>
        <HistoryContext.Provider value={history}> {/*useParams (react-router) works so but only for V5 with this fix */}
            <MyChildComponent/> {/*useDispatch (redux), useStore (zustand) doesn't work :( */}
        </HistoryContext.Provider>
    </RouterContext.Provider>
</Scene>
```

Thanks.

**Comment by brianzinn** [comment]
Good question @saidmoya12  -- It's a known "bug" with React context crossing renderer boundaries.  Are you able to make a bridge like this?
https://github.com/brianzinn/react-babylonjs/blob/master/packages/storybook/stories/babylonjs/Basic/contextBridge.stories.js#L28

You should only need to do it once to bring it across into your `<Scene>...</Scene>`.

**Comment by brianzinn** [comment]
Thanks for adding to the conversation @cjjkoko, but it looks like it does not capture the context before the renderer switches!  

Closing from inactivity - please re-open if you have more feedback.  There is also a generic way to bridge the context in drei (https://github.com/pmndrs/drei#usecontextbridge).

**Comment by drcmda** [comment]
@brianzinn https://github.com/pmndrs/its-fine this solves the issue completely. we will be using this ootb for canvas from now on.

**Comment by brianzinn** [comment]
@drcmda - let me know when you bring that into r3f (it sounds like that is your intention) -- Very interested to look at how you will integrate it and would consider adding as a dep - lots of people get caught up on the renderer boundary.  I've been switching all my demos to `zustand` as it solves the renderer boundary issues seamlessly.

Looks like I just `useContextBridge` and flow the `{children}` to the bridge with a `react-nil` render.   Highly cool.
