### ISSUE TITLE
version:3.1.10   EcmaScript Module 

### ISSUE THREAD

**Issue by cjjkoko** [brianzinn/react-babylonjs#243]
At new version, I got this issue:(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').

https://github.com/brianzinn/react-babylonjs/blob/master/packages/react-babylonjs/src/ReactBabylonJSHostConfig.ts

I change  
```
import {
  DiscreteEventPriority,
  ContinuousEventPriority,
  DefaultEventPriority,
} from 'react-reconciler/constants'
```

to

```
import {
  DiscreteEventPriority,
  ContinuousEventPriority,
  DefaultEventPriority,
} from 'react-reconciler/constants.js'
```
can resolve this issue

**Comment by fliptrail** [comment]
You can also do a separate `npm i react-reconciler`. It will update it to the latest version.

**Comment by brianzinn** [comment]
thanks @cjjkoko for reporting that and helping me work through these issues!!  Hope it's working for you now 😄

**Comment by cjjkoko** [comment]
@brianzinn thanks
