### ISSUE TITLE
<pbrMaterial> are not fully supported for all properties

### ISSUE THREAD

**Issue by aliwangzai** [brianzinn/react-babylonjs#259]
Hi, 
pbrMaterial does not support propery like "isFractionEnabled"
I am new to React ,  I tried to modify the source code . I didn't get this to work ! :(

**Comment by brianzinn** [comment]
hi @aliwangzai  -- Only properties from the API are supported.
https://doc.babylonjs.com/typedoc/classes/BABYLON.PBRMaterial

Have you added your own properties?

**Comment by aliwangzai** [comment]
I see ,I just want change the property by code .  some properties beyond the API  but actually exists in the Inspector Editor of Material .  😃 ,maybe the property  are not exposed yet ?

**Comment by brianzinn** [comment]
Can you show a screenshot of where you see this?  I can't find it anywhere:
https://github.com/BabylonJS/Babylon.js/search?q=isFractionEnabled

**Comment by aliwangzai** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/5028177/203197672-5637f072-c1b5-45d9-8105-3d0d8accd2a2.png">
 above , there are also other properties not being exposed

**Comment by aliwangzai** [comment]
<img width="334" alt="image" src="https://user-images.githubusercontent.com/5028177/203197672-5637f072-c1b5-45d9-8105-3d0d8accd2a2.png">
 above , there are also other properties not being exposed

**Comment by aliwangzai** [comment]
Thanks for ur help !
