### ISSUE TITLE
Html element flickering (new)

### ISSUE THREAD

**Issue by DenysAshikhin** [brianzinn/react-babylonjs#260]
Hi,

First of all, thank you for creating + maintaining this library, *and* being pretty quick + helpful when questions/issues arise. That being said, I have an issue that wasn't present before where the Html element flickers (gets rerendered?). 
Demo: https://youtu.be/JuEgflt4C60

This wasn't an issue before, I'm not sure when it started exactly but it wasn't always there until more recently. I tried recreating a code sandbox for this, but I couldn't get it working with the exact version of react, babylonjs and react-babylons. Here is the demo with older versions demo:
https://codesandbox.io/s/suspicious-pond-5xjdw9

Current library versions:
```
 "react": "^18.2.0",
    "react-babylonjs": "^3.1.13",
"react-scripts": "^5.0.1",
"@babylonjs/core": "^5.27.1",
    "@babylonjs/gui": "^5.27.1",
    "@babylonjs/loaders": "^5.27.1"
```

That said, in the older demo, the bug doesn't seem to reproduce, but it should at least show what is going on in my code. Where I have a parent component that fetches data and passes it to my scene + individual models (which have and Html element much like the box in demo) that follows them around. However, every time it fetches the data there is a refresh that causes a flicker. In the demo, I use the `setInterval` to replicate the `setState` trigger, which does cause a rerender of the Html element, but it is no longer flickering.

My guess is maybe it has something to do with the library versions on the demo being older?

**Comment by dennemark** [comment]
I have just created a PR (independently of your issue :D) that changes the render hook of HTML from onBeforeRender to onAfterRender. Maybe this solves already the issue?
Otherwise I will need to have a look at it again.

Your sandbox does not show an html component.

**Comment by DenysAshikhin** [comment]
Really sorry about that, I updated the sandbox

**Comment by dennemark** [comment]
Can you reproduce it in a codesandbox? 
I updated dependencies and could not reproduce: https://codesandbox.io/s/affectionate-hypatia-w7rqz6?file=/src/App.tsx

But the way you describe it with the refetch, I am wondering, if the Html component is being remounted every time?
Any chance you could keep the wrapping Html alive?

```
const ComponentThatFetches = ()=>{
const fetchedData = useQuery()

return <Html>
   <PopupDiv>
    {fetchedData && <MyInnerHtmlComponent data={fetchedData}/>}
   </PopupDiv>
</Html>
}
```

**Comment by DenysAshikhin** [comment]
When you say keep the wrapping Html alive, do you mean not behind a conditional render?


```
  <box
      name={name}
      ref={boxRef}
      size={1}
      position={internalPosition}
      scaling={scaling}
      width={1}
      height={1}
      depth={1}
      visibility={1}
    >
      <standardMaterial
        name={`${name}-mat`}
        diffuseColor={color}
        specularColor={Color3.Black()}
      />
      {/** Sits on top of outer box */}
      <box
        name={name}
        size={0.1}
        position={new Vector3(0, factoryDimensions.yShift ,factoryDimensions ? factoryDimensions.zMax * 0.065: 0)}
        visibility={0}
        color={new Color3(255, 0, 0)}
      >
            <Html
            name="html"
          >
            {
              <MachineStatus
              cameraMode={cameraMode}
                threeD={true}
                cameraRadius={cameraRadius}
                machine={machine}
                activeMachine={activeMachine}
                setActiveMachine={setActiveMachine}
                scalePoint={scalePoint}
                zoomSnap={zoomSnap}
                resetInfoHover={resetInfoHover}
              />
            }
          </Html>
      </box>
    </box>
```
That's what it looks like from my current code - so I don't think (?) I'm loosing the wrapping html

**Comment by dennemark** [comment]
What happens, if you just display some div with text, instead of MachineStatus within that component?
You are not using occlude on Html right?
As soon as @brianzinn pushes the next version, we could try it with the updated Html component.

**Comment by DenysAshikhin** [comment]
Yea, I'm not using occlude. Also I tried simly:

```
  <Html name="html">
          <div style={{ width: "64px", height: "64px", backgroundColor:'white'}}>
Test
          </div>
   </Html>
```
and it's the same result.
I've also added a few more conditional renders to better show how my code is structured - but I still can't cause it to flicker on the codepen (https://codesandbox.io/s/blissful-lamport-jxeugm?file=/src/App.tsx)

**Comment by brianzinn** [comment]
sorry I didn't publish earlier.  can you try `3.1.14` with the render update?

**Comment by dennemark** [comment]
Try this: https://codesandbox.io/s/priceless-khorana-uusur0?file=/src/App.tsx

It has its own implementation of Html. It also uses Tunneling - I just named it this way... If you prefer a library, stick to tunnel-rats, but their version does not include hot module reloading as well as the order of Html Elements could change.
You can also create a tunnel the other way around. Send babylon data from react-dom to react-babylonjs scene.
It has benefits over the current Html implementation, since it does not create a react renderer for each html element, but places the elements within the existing react-dom renderer.
But it has few more dependencies: zustand and a uuid generator (@thi.ng/random) to track each Html element 

Some older version can be found in storybook or here: https://github.com/brianzinn/react-babylonjs/pull/168

**Comment by DenysAshikhin** [comment]
That looks promising! I tried to incoporate the solution as the extra libraries aren't a problem, however, I have never worked with typescript (comfortable with typings, just not typescript itself). And my whole project is just JS. I'm running into some issues trying to make it work.

I did my best in my codepen: https://codesandbox.io/s/blissful-lamport-jxeugm?file=/src/Html.jsx
I would greatly appreciate it if you could do the final touches to show me where I'm going wrong!

**Comment by DenysAshikhin** [comment]
Just an update that I used [this](https://www.typescriptlang.org/play?#code/PQKhCgAIUgBBbA9gEwK4BsCmkBimCGALgGoCWmA7gA6IBOhwAxovDQHaZuEDOwAEgBUAsgBkoIYOFKs6hSAG9IqVKWSQAvpABmtFpABEsQgAtSAOjYBzYLXxtkLfQG4pM+gqi5bl+J0IAaTwAlAkZCADkUTEDIJW5MAGF8dHQAI3xGAGsYuMwRfABPRFRCAFEtLUwwnNR4oUwkcE0dPX1aUMJnVxp3RnaibBb4AwAvWsI7ZC7wQgKqbAAFXSpuSABeBUhGU3RkdrYALkgQjIiojRcZuewAZQnCbA35T0ZUWn3CI5DmWmQAHm4hFopCs-mOHUiyEwAD4XLEAG6YWjcUiIQ6QNioeCpJFwyDAYCQeKfSB3OiYACCVFIfzuA2hAG0AOTEukPJkAXSaLlm80gAlQbA46DJ7XWHlihEFwu4XyqdH+gOBoMgC3w9FIyVp9xhsM8xIFQsw6COAApMpgCkclSDLGDUFRkAMcOjTYCBkc2ZgAJTraGq9WETXobX031rf3wxCqFzqFzMNiA3Kix5bfoPP6G4Up6Gmt2YQjh-2m56S6XG2UKdQ5A3lk2Qc2W+2Oga0F1FiWxIkFvPuh4d0td2IJpNSo3ocWDofDt4fI7yaueaeQRHI1HogAMOWXZl3fcwZjHMoZFoKXOXcaXXfaUtobE7y6PFfnV53e51h7r3G3y8gJ8tHIvr+067p+44-sBoEOk6DxtmwppPug3qvtO6gobEaEXniGHeniaHqN6uHgJgAAePRyFCWj4BgchaIKYTrpAiGNlaRJAravqDjebz3lOkAAJKuoo2ykLs+waEcSyICsA4oSOci1uO4q1JgKa9jqHb7mYinCkRy7ySuSIomiynxGp6G5EkKTpFk6kDJpH6Idw-5ngA-GYq7GfermuZAW5-qeHLIcuRFyWiSaqKZmD1EgeYdsoqimt6YIMkF2FdqAkAAOrGJwTGmKszAyBwXCQEggo8GCFDYCCfQEPE+XYIC5IsoZa4mZi2JImYKECAVkAUKJE6MNRDXJBOpGkICtqQLYPBMYgs2YAAtPsUK0A2ABW4yQOgpAWpApBaI1kAAPIlFsLDsH4KHVWK8D4FQ1JWIdDzwKshCLfgu1TYQZi+n12DtKtnDrTNg0pFso3YCYgwgskKEKkikCIMda1IpgahFddXAfYtD2ENsA3GEQJ0qRtU2QKR8wMVYZjQJIy4qfkRQlOUlRhHFfoPtOOnGixYJuhp3MlhZCJGeu1ofp5jEANSQAAjBZBF6ahKVpeAKGZRSbAFEx0gw7lWw7HseUAPp0GbJ3Ne0rUyx1WI4ht2x2JY0SHYmSKEChsNEjTR3kGoJxhMbomm-eIKfSde1Jqjs1ENw9MSChzOFMUZQVFUhBcxGPNDkdDYiWJnCcWL3aEFm-OnoLwmzn4GgdqLwFDq87x+POkCga3HwpaogGh8X96Yc3KuXM3S23veSV+mXsR8+gAsNrXbelQR3N8ePBmKAyfdHPCySoO7oEcBQXoaOK3d+Ol4-cXemyX1wRwn2fl7jzh19dsPQ7Vn+Rfh2C9s2AaxQrfe8mIUjpUXFec6JJp65w3pdRMcgH5yA2CpcywEVJWTSBkTIdl+zcy0k5FyHJ3IoMgD5KsKVArBWnKrIcoCGwWT+NCMu8hTqpE2lnMwp5uCmhQd6MwD0qB5lPLJN+E8eKQD+DgbwvhSqnjWPIU86hoTyBQSQ9QfxgCyPwD4Pwepx4ES-tObRrCQqQM8JeNCQA) to auto convert the TS to JS. Did some code tweaking on my local machine and it worked!

I can mark this as solved, but I don't know if this would be considered a proper solution or a band-aid one?

Also a final question regarding the random generation of ID's. Can I get rid of that dependency if I have my own way of uniquely ID'ing each html element?

**Comment by dennemark** [comment]
Very nice! I tried to convert, but there were more issues than expected, so I had to postpone it. Nice that it worked.

Sure you can use your own random ID´s. I just used it out of convenience.


I guess it should be also possible to deal with the ids without use of external dependencies, i.e. just by using a counter.
Anyhow would be nice to know, if @brianzinn would prefer to have additional dependencies (zustand? - its really small) within react-babylonjs or an additional package.
Zustand could also be a good replacement, when using useScene or useEngine. Currently they cannot be consumed outside of Engine context. It would lead to issues though, if using multiple engines or scenes.

**Comment by DenysAshikhin** [comment]
Right, in my case each element is already tied to a unique ID so I don't strictly speaking need the uuid. But I will leave it anyway in case I need to use the HTML for something else. I won't mark it as resolved just yet as I would like to get @brianzinn opinion on it and we can close it then. Just for conveniency, my working (JS + TS hybrid repo) [HERE](https://codesandbox.io/s/blissful-lamport-jxeugm?file=/src/Html.jsx)
And pure, clean TS from @dennemark [HERE](https://codesandbox.io/s/priceless-khorana-uusur0?file=/src/App.tsx)

**Comment by brianzinn** [comment]
I am open to zustand for sure.  It's inconvenient to need to declare components in the Scene (to get Scene access), but like you said there is a trade-off and probably just need to doc some recipes.  The other disadvantage of right now is needing to bridge across context boundaries, so I always recommend zustand over redux, for example.

**Comment by DenysAshikhin** [comment]
In that case, I'll leave this open for a few days in case I notice something else odd with this implementation. If not, I will silently close it. Thanks for all your help guys!

**Comment by DenysAshikhin** [comment]
@dennemark I would also be open to getting into a call + screen share since the code on my end isn't anything overly complex. And the problem happens right away, so perhaps we can do some on-the-spot logging to try and recreate it inside a code pen?

**Comment by DenysAshikhin** [comment]
I've narrowed the problem on my side to my div's being `position: 'absolute'`. However, this behavior is not being replicated in the code pen. When I remove the `absolute` then it fixes it from being moved to the bottom (0,0) but instead, it seems to take up space in a difference div (a scrollbar appears) and then immediately disappears. 

My impression is when the div gets mounted/changed it gets placed outside the normal div? hierarchy which makes the DOM act funny, and then after the first render it is placed correctly. Again, I am very open to hopping into a call whenever you are available to better show this as I am struggling to recreate this interaction of (modified tunnel + HTML) in a small codepen.

**Comment by dennemark** [comment]
Hi Denys, these days I am a bit busy. Not sure when I find time. If I manage, I will let you know!
The HTML element itself is placed as absolute element. It has a center={true} attribute to be centered. Maybe interesting for you?

In my case I have placed the tunnel out next to the engine within a relatively positioned div container, which should deal with absolute positioned elements in it. Roughly like the following code

```
<div
      id="engine-wrapper"
style={{
      position: 'relative',
      width: "100%",
      height: "100%",
      overflow: 'hidden'  //not sure if you need this
     zIndex: 1  //not sure if you need this
}}
    >
      <Engine>
{children}
</Engine>
<Tunnel.Out />
</div>
```

**Comment by brianzinn** [comment]
You could potentially flow in the zIndex as a prop here - I am not familiar 100% with that code though....
https://github.com/brianzinn/react-babylonjs/blob/master/packages/react-babylonjs/src/customComponents/Html.tsx#L335
`{zIndexProp ?? objectZIndex(...)}`
You'd need to add it to the dependency array for after render.

**Comment by DefaultV** [comment]
I've also experienced this issue, it seems to be when updating the root scene / engine component while having a <Html> component as a child.

```
...
const [clearColor, setClearColor] = useState<Color4>(
    Color4.FromHexString("#000000FF")
  );

setInterval(() => setClearColor(Color4.FromHexString("#000000FF")), 500);
...

<Scene clearColor={clearColor}> ... </Scene>
```

Reproducible branch:
https://github.com/DefaultV/create-react-app-typescript-babylonjs/tree/bug-htmlflicker

Video:

https://user-images.githubusercontent.com/14123880/207896506-d46df015-d97a-4a36-9dc8-ba22b2206ce3.mp4

**Comment by DenysAshikhin** [comment]
Oh that looks good, and seems like it has another source of the issue, that's not just a ton of html's being rendered at once. 

Also @brianzinn I am still waiting to implement your suggestion, work just shifted some priorities around so I'm fighting to get some time to return to this

**Comment by dennemark** [comment]
@DefaultV does this also happen, when you place the Html in its own component? So the component with scene just has something like <Component /> ?

It might be better to update clearColor on the scene directly, and not on the virtual react component. I.e. via useRef

**Comment by DefaultV** [comment]
@dennemark I haven't tested that no, but I'm sure it's the same (That's the setup on my project).

The thing is, if you want to interact with a HTML UI, e.g.
```
div
   canvas
   ui
/div
```
You will need some sort of UI/global context, which will cover the <Engine and <Scene components, thereby forcing a react render when you update the context.

I can imagine that this use-case is quite prominent, but I'm open to hear other ways of dealing with a HTML UI

**Comment by dennemark** [comment]
@DefaultV I would have to check. But the tunnel approach that is linked above in a codesandbox uses zustand and is pretty smart concerning rerenders. So I guess the Engine and Scene wont be rerendered.

**Comment by brianzinn** [comment]
closing from inactivity.  looks like there is a workaround.  if there is an issue or feature request - kindly re-open or preferably create new issue, since this one will have unrelated history. Thank-you for your contributions.
