### ISSUE TITLE
Standard Material diffuse texture no uoffset and uscale property

### ISSUE THREAD

**Issue by jinincarnate** [brianzinn/react-babylonjs#264]
how to set a textures uOffset or uScale property for tiling purpose

**Comment by brianzinn** [comment]
@jinincarnate  How are you doing it now - ie: this does not work?
```
<texture
    url="assets/textures/diffuse.png"
    assignTo="diffuseTexture"
    uScale={textureUScale}
    uOffset={textureUOffset}
/>
```

ref: https://doc.babylonjs.com/typedoc/classes/BABYLON.Texture#uScale

**Comment by jinincarnate** [comment]
`<standardMaterial
        name="media_material"
        roughness={1}
        emissiveColor={Color3.FromHexString('#000000')}
        specularColor={Color3.Black()}
        ref={mediaMaterialRef}
      />`

`const [mediaMaterial, setMediaMaterial] = useState<StandardMaterial | null>(
    null
  );

  const mediaMaterialRef = useCallback((node: any) => {
    if (node) {
      setMediaMaterial(node);
    }
  }, []);`

mediaMaterial.diffuseTexture. doesn't have uOffset

**Comment by brianzinn** [comment]
can you share a working codesandbox or babylonjs playground?

**Comment by DefaultV** [comment]
This is because the type for the diffuseTexture is BaseTexture, which doesn't have the property. If you cast it, you should get your available options:
`(material.diffuseTexture as Texture).uScale = 2`

https://doc.babylonjs.com/typedoc/classes/BABYLON.BaseTexture

**Comment by jinincarnate** [comment]
Thank you so much that was the exact case

**Comment by brianzinn** [comment]
you should also be able to do:
```
<standardMaterial name="media_material" ,,, >
  <texture assignFrom='diffuseTexture' uScale={2} />
</standardMaterial>
```
