### ISSUE TITLE
Filed to compile

### ISSUE THREAD

**Issue by Nienormalny** [brianzinn/react-babylonjs#27]
**My import to react:**
`import {Engine, Scene, FreeCamera, HemisphericLight, Sphere, Ground} from 'react-babylonjs';`

**My Code:**

`<Engine canvasId="render-labyrinth">
<Scene>
<FreeCamera name="player" position={new Vector3(0, 5, -10)} target={Vector3.Zero()}/>
<HemisphericLight name="light" intensity={0.7} direction={Vector3.Up()}/>
<Sphere name="sphere1" diameter={2} segments={16} position={new Vector3(0, 1, 0)} />
<Ground name="ground1" width={6} height={6} subdivisions={2}  />
</Scene>
</Engine>`

**Error in terminal:**

`./node_modules/react-babylonjs/dist/react-babylonjs.es5.js`
`Module not found: Can't resolve 'babylonjs-gui' in '...\node_modules\react-babylonjs\dist'`

**Comment by brianzinn** [comment]
hi @Nienormalny - thanks for the report.  'babylonjs-gui' is a peer dependency only, so you should be able to run without as long as you are not referencing it.  Maybe you could try:
`yarn add babylonjs-gui`?
I can try to reproduce later tonight and see if it's useable without importing, although I am nearly ready for a v2...

**Comment by brianzinn** [comment]
Does this demo repo solve it for you?  It's `react-babylonjs` v2 and using es6 `@babylonjs/*`.
https://github.com/brianzinn/create-react-app-typescript-babylonjs

**Comment by brianzinn** [comment]
Should be fixed and can be verified from repo linked in previous comment.  Please reopen if you have any questions or issues with `react-babylonjs` v2.
