### ISSUE TITLE
Will there be hook versions of all the HOCs?

### ISSUE THREAD

**Issue by andrewpeterprifer** [brianzinn/react-babylonjs#28]
I think a nice (and easy to implement?) addition to the API would be hook versions of the the 2(?) HOCs, something like `useBabylonJS` and `useScene`.

**Comment by konsumer** [comment]
It uses [context](https://reactjs.org/docs/context.html), so it should be simple as simple as this:

```js
import { SceneContext } from 'react-babylonjs'
const useBabylonJS = () => React.useContext(SceneContext)

// then later

const { engine, canvas, scene } = useBabylonJS()
```

**Comment by konsumer** [comment]
I wrote the original HOCs (before hooks), but I'm not really a typescript guy, so it's a bit hard for me to work with typedefs and follow the code-style without a lot of effort. You can see where the contexts are [here](https://github.com/brianzinn/react-babylonjs/blob/master/src/react-babylonjs.ts) which points to [Scene](https://github.com/brianzinn/react-babylonjs/blob/master/src/Scene.tsx#L32-L36) and [Engine](https://github.com/brianzinn/react-babylonjs/blob/master/src/Engine.tsx#L13-L16). The 2 useful HOCs there are `withBabylonJS` and `withScene` as you mentioned.

So in JS, in [Engine.tsx](https://github.com/brianzinn/react-babylonjs/blob/master/src/Engine.tsx):
```js
export const useBabylonJS = () => React.useContext(BabylonJSContext)
```

and in [Scene.tsx](https://github.com/brianzinn/react-babylonjs/blob/master/src/Scene.tsx):

```js
export const useScene = () => React.useContext(SceneContext)
```

then make sure they are exported in [react-babylonjs.ts](https://github.com/brianzinn/react-babylonjs/blob/master/src/react-babylonjs.ts)

**Comment by konsumer** [comment]
Further, if you wanted it to export a simpler object:

```js
export const useBabylonJS = () => React.useContext(BabylonJSContext).engine
export const useScene = () => React.useContext(SceneContext).scene

// usage

const engine = useBabylonJS()
const scene = useScene()
```

Wrapping context like this has virtually 0-cost, so you could make a hook for getting canvas, too, even though it's the same context:

```js
export const useCanvas = () => React.useContext(BabylonJSContext).canvas
```
