### ISSUE TITLE
Model property scaleToDimension

### ISSUE THREAD

**Issue by jinincarnate** [brianzinn/react-babylonjs#281]
what is the model property scaleToDimension is it used for.

`<Model
            key={counter}
            name={sceneName.split('.')[0]}
            reportProgress
            position={new Vector3(0, 0, 0)}
            rootUrl="models/"
            sceneFilename="test.glb"
            scaleToDimension={400.0}
            onModelLoaded={(model) => onLoaded(model)}
            id="someid"
          />`

**Comment by brianzinn** [comment]
it's meant to scale to the largest dimension.  so what you have there is to scale the object to 400 meters.

If the longest dimension of your bounding box is 4, for example, then it will scale x 100 (make it 100 times larger).  I typically use that property to fit different models into a specific space - it was originally designed for a remix 3d mashup that I made.  It should be optional and then leaving it out will not do any scaling.
