### ISSUE TITLE
WebGPU Support

### ISSUE THREAD

**Issue by zhangyahan** [brianzinn/react-babylonjs#283]
https://forum.babylonjs.com/t/how-to-enable-webgpu-in-react-babylonjs/38197/5.
as mentioned here, support webgpu. If the author's time does not allow, i want pull a request.

**Comment by brianzinn** [comment]
hi @zhangyahan  - would definitely accept a PR!  cheers.

**Comment by buuhvprojects** [comment]
have it support to webgpu?

**Comment by brianzinn** [comment]
i have a PR #315 - looking for any feedback on the design.  there was a community PR #289 .  If you have any feedback between the 2 different ways. Thanks.

**Comment by buuhvprojects** [comment]
@brianzinn in my opinion your PR is better cause it include more features e its prepared for fallbacks e errors

**Comment by brianzinn** [comment]
closing.  Available in v-next via `<WebGPUEngine ... />` and `<FallbackEngine ../>`.
