### ISSUE TITLE
How to include and control animation playback?

### ISSUE THREAD

**Issue by andrewpeterprifer** [brianzinn/react-babylonjs#29]
How would I go about loading an animation from a GLTF file and controlling its playback? I think this would be a nice example to add to the GH page.

**Comment by brianzinn** [comment]
In the `onModelLoaded()` callback when the GLTF is loaded you get passed the animation groups.  Here is a demo that demonstrates the callback:
https://brianzinn.github.io/react-babylonjs/?path=/story/babylon-basic--model-atom-gsap-tween

You can, for example, used animated GLTF from here:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BrainStem/glTF

To track the progress of the animation, you would just need to register once the model is loaded:
```javascript
onModelLoaded = (model, {scene}) => {
  var lastProgress = 0;
  var onRenderObservable = () => {
    var defaultAnimationGroup = model.animationGroups[0]
    var totalFrames = defaultAnimationGroup.to - defaultAnimationGroup.from;

    var currentFrame = (defaultAnimationGroup.targetedAnimations[0] && defaultAnimationGroup.targetedAnimations[0].animation.runtimeAnimations[0])
      ? defaultAnimationGroup.targetedAnimations[0].animation.runtimeAnimations[0].currentFrame - defaultAnimationGroup.from
      : 0;
    var currentProgress = Math.round(currentFrame/totalFrames * 100) / 100;
    // just to reduce console logging...
    if (currentProgress != lastProgress) {
      lastProgress = currentProgress;
      console.log(`animation progress: ${currentFrame}/${totalFrames}`, currentProgress)
    }
  }

  // TODO: remove observable when your component unmounts
  scene.onBeforeRenderObservable.add(onRenderObservable)
}
```

The first animation [0] is played by default, but what you would want to do is list the name of each of the animations if you wanted them selectable in your application (each group has a `name`.  Each animation group has methods like `play(loop?: boolean)`, `stop()`, etc.  To control the playback you also have `goToFrame()`.  You would need to manage some state to control playback.  I don't know a declarative way to do that, so it's not part of the `Model` component or this project.  If you want to propose some additions they would be welcome.  For non-GLTFs then you may need to make AnimationGroups from the skeleton animatables.  This would have been a lot easier to make an example from in the CRA project with redux and buttons...  :) Thanks for the feedback.
