### ISSUE TITLE
advancedDynamicTextureMaterial keeps dangling even when the component is unmounted

### ISSUE THREAD

**Issue by jinincarnate** [brianzinn/react-babylonjs#290]
Hi I have created a 3d UI in VR using a similar code as shown in the link below 

https://brianzinn.github.io/react-babylonjs/examples/gui/2d-gui

but when the component is unmounted all objects like plane, advancedDynamicTexture, and all other ui components gets destroyed, but advancedDynamicTextureMaterial (that gets created automatically) doesn't get disposed and keeps hanging in the scene. Is there a way to get its reference so that it can be disposed.

**Comment by brianzinn** [comment]
do you know the imperative solution?  if you can make a regular babylon PG then I'm sure we can figure it out.

**Comment by jinincarnate** [comment]
Hi i have tried adding babylonjs inspector to your example so that the issue can be seen easily. the code might run a lil slow just tried to cook up something fast.

Try it on [https://codesandbox.io/s/relaxed-solomon-75zjci](https://codesandbox.io/s/relaxed-solomon-75zjci)

![image](https://github.com/brianzinn/react-babylonjs/assets/9129660/70d146e4-2d9f-4d13-b735-900fdeda6a5c)

as u can see in the image multiple instances of advanced dynamic texture material are getting created as we open and close the 3d UI

**Comment by brianzinn** [comment]
@jinincarnate can you confirm it's fixed in `3.1.17`?

**Comment by jinincarnate** [comment]
looks like solved
