### ISSUE TITLE
Migrating from individual models to instances

### ISSUE THREAD

**Issue by DenysAshikhin** [brianzinn/react-babylonjs#297]
Hi,

I am currently creating copies/clones of the same model using:

```
  <Model
        rootUrl={`./`}
        sceneFilename={`cavity_blocks.glb?id=${id}`}
        scaleToDimension={toScale ? toScale : 10}
        position={display ? currentCoord : new Vector3(9999999, 9999999, 99999999)}
        rotation={rotation}
        onModelLoaded={onModelLoaded}
        onLoadProgress={updateProgress}
      ></Model>
```

Inside of `OnModelLoaded` I'm also grabbing the mesh reference:
```
const onModelLoaded = (model) =>{
 coreRef.current = model.rootMesh;
 }
 ```
 
 Then I am moving individual models with a `useBeforeRender`:
 
 ```
   useBeforeRender(
    (scene) => {
      if (display && isVisible)
        if (coreRef.current && tag.threeX && factoryDimensions.width !== 0) {
          var deltaTimeInMillis = scene.getEngine().getDeltaTime();

          let xDiff = coreRef.current.position.x - targetCoord.x;
          let zDiff = coreRef.current.position.y - targetCoord.y;
          let yDiff = coreRef.current.position.z - targetCoord.z;

          let distance = Math.pow(xDiff, 2) + Math.pow(yDiff, 2);

          if (distance > 0.25) {
      
            let xMove = (targetCoord.x - previousCoord.x) / 1000;
            let yMove = (targetCoord.z - previousCoord.z) / 1000;
            let zMove = (targetCoord.y - previousCoord.y) / 1000;

            coreRef.current.lookAt(targetCoord);
            coreRef.current.rotation = new Vector3(
              coreRef.current.rotation.x + Math.PI / 2,
              coreRef.current.rotation.y,
              coreRef.current.rotation.z - Math.PI / 2
            );
          
            coreRef.current.position.x += deltaTimeInMillis * xMove;
            coreRef.current.position.z += deltaTimeInMillis * yMove;
            coreRef.current.position.y += deltaTimeInMillis * zMove;
          }
        }
    },
    undefined,
    undefined,
    undefined,
    [tag, factoryDimensions, coreRef, coreRef.current, boxRef, targetCoord, previousCoord, isVisible, trajectoryCoord]
  );
 ```

Is it possible to achieve this using instances? The meshes are static, and only their individual location/rotation is updated as in the beforeRenderLoop. If it is, can someone guide the start? I have tried going over the doc for assetManager and mesh from instance but I'm not sure how to combine these things

**Comment by brianzinn** [comment]
The Model component doesn’t do much. Just a wrapper for a scene loader hook:
https://github.com/brianzinn/react-babylonjs/blob/master/packages/react-babylonjs/src/customComponents/Model.tsx#L55

If you have captured that mesh reference then you can declaratively use “InstancedMesh” or create instance yourself and use “fromInstance” prop on a “Mesh”. Don’t let the name of the property mislead you as it is available on ALL declared types.

**Comment by DenysAshikhin** [comment]
So I used the 
```
<Model 
onLoad={(root_mesh)=>{
root_mesh_ref.current = root_mesh}}

/Model>
```

Then later:
```
<Mesh
fromInstance={root_mesh_ref.current}
/>
```


Except I get:
```
ReactBabylonJSHostConfig.ts:481 fromInstance wrong type. AbstractMesh {_isDirty: true, _nodeDataStorage: _InternalNodeDataInfo, state: '', metadata: null, reservedDataStore: null, …} class Mesh extends _abstractMesh_js__WEBPACK_IMPORTED_MODULE_13__.AbstractMesh {
  /**
   * @constructor
   * @param name The value used by scene.getMeshByName() to do a lookup.
   * @param scene The scene… 
    at Mesh
    at Suspense
    at CoreModel (http://localhost:3000/static/js/src_assets_3d_icon_svg-src_assets_Exit_Fullscreen_svg-src_assets_Fullscreen_svg-src_assets_Ma-1115ee.chunk.js:7805:5)
    ```
    Am I doing it wrong?

**Comment by DenysAshikhin** [comment]
Swapping to abstractMesh leads to no errors, but no model or anything shows up

```
  <abstractMesh
                      fromInstance={cavity_block_ref.current.rootMesh}
                      position={new Vector3(10, 10, 10)}
                      name={`core_block.glb?id=${3132132133115}-model`}
                    />
                    ```

**Comment by brianzinn** [comment]
hi, sorry i didn't notice a reply.

For the abstract mesh.  I would expect it to move the position of the loaded model, if that was the last positional update.  You may want to be specific with the prop `disposeOnUnmount`.  You can verify that in the Inspector.

For the instancedMesh one.  If you are using the code in your original message then you have destructured the parameter incorrectly.  I think that may be the cause of the other one as well.  Do a console.log or look at the properties of "rootMesh" parameter.  The object being returned is actually a loaded model with animations, animation groups, etc:
https://github.com/brianzinn/react-babylonjs/blob/master/packages/react-babylonjs/src/hooks/loaders/loadedModel.ts#L15

The code you likely want is not
```jsx
<Model 
  onLoad={(root_mesh)=>{
    root_mesh_ref.current = root_mesh
  }}
</Model>
```
but instead
```jsx
<Model 
  onModelLoaded={({rootMesh})=>{
    root_mesh_ref.current = rootMesh
  }}
</Model>
```
or
```jsx
<Model 
  onModelLoaded={(loadedModel)=>{
    root_mesh_ref.current = loadedModel.rootMesh
  }}
</Model>
```

Your editor should be telling you all of this.  If you are using TypeScript and you strongly type your `useRef<T>` then you will know as well.
![image](https://github.com/brianzinn/react-babylonjs/assets/542756/1c67a5a2-064f-4862-9b14-3c2a26528d3f)

**Comment by DenysAshikhin** [comment]
Long time no chat!

So I got it to work with <abstratMesh /> doing the following:


```
<>

    <Suspense fallback={<box name="fallback" position={new Vector3(0, 0, 0)} />}>
                    <Model
                      ref={cavity_ref_temp}
                      rootUrl={ `./`}
                      sceneFilename={`cavity_blocks_compressed.glb?id=sample_instance_root3332`}
                      position={new Vector3(20, 20, 20)}
                      onModelLoaded={(rootMesh) => {
                        cavity_block_ref.current = rootMesh;
                        console.log(`setting cavity_block_ref:`);
                        setTimeout(() => {
                          setCavityBlockLoaded(true);
                        }, 2000);
                      }}
                    />
       </Suspense>
       
       
        {cavityBlockLoaded && (
                  <>
                
                    { <abstractMesh
                      fromInstance={cavity_block_ref.current.rootMesh}
                      position={new Vector3(1, 10, 1)}
                      name={`cavity_blocks_compressed2.glb?id=${31115}-model`}
                    />
                    <abstractMesh
                      fromInstance={cavity_block_ref.current.rootMesh}
                      position={new Vector3(10, 1, 1)}
                      name={`cavity_blocks_compressed3.glb?id=${33212315}-model`}
                    /> 
                  </>
                )}
</>

```

However, only the last abstract mesh is visible, the original <model> and the first <abstractMesh> is not showing up, it seems like they are just controlling the same mesh position.

I tried using 

```
     <instancedMesh
                      source={cavity_block_ref.current.rootMesh}
                      position={new Vector3(10, 1, 1)}
                      name={`cavity_blocks_compressed3.glb?id=${33212315}-model`}
                    /> 

```

But that thew a bunch of console errors - any ideas what I need to tweak to create seperate instances of the initial model?

**Comment by brianzinn** [comment]
@DenysAshikhin try on `3.1.26` that was just published.  It will let you use `<Model ref={...} />` as you have done.

**Comment by DenysAshikhin** [comment]
Sounds good, let me give it a shot!

**Comment by DenysAshikhin** [comment]
Updating fails to compile now: 
![image](https://github.com/brianzinn/react-babylonjs/assets/10791321/de8cf415-f08b-4d30-9518-bf3191a20d14)

My package.json:
![image](https://github.com/brianzinn/react-babylonjs/assets/10791321/899d3ec8-9f0b-40a5-a39d-01d946cf4317)
![image](https://github.com/brianzinn/react-babylonjs/assets/10791321/8c2ef53f-737f-4231-b65c-b30c2b24a6c2)

**Comment by brianzinn** [comment]
It’s been renamed recently. Are you able to go to latest?

**Comment by DenysAshikhin** [comment]
Sorry, which library to go latest?

**Comment by brianzinn** [comment]
@babylonjs.

**Comment by DenysAshikhin** [comment]
Okay we are back up and running but I get the following stack:
![image](https://github.com/brianzinn/react-babylonjs/assets/10791321/e7a06335-84e4-4dd0-951f-5f6c88abcc05)
Am I supposed to use the red or green ref for instancedMesh?


![image](https://github.com/brianzinn/react-babylonjs/assets/10791321/834b1b50-866d-4865-8b26-c6f9aadcb8d2)

**Comment by brianzinn** [comment]
I would say you would use `cavity_ref_temp.current` for the instancedMesh.

**Comment by DenysAshikhin** [comment]
![image](https://github.com/brianzinn/react-babylonjs/assets/10791321/fcdce2f1-0510-4a8a-b65b-7cd728147c0f)
![image](https://github.com/brianzinn/react-babylonjs/assets/10791321/ad7ef48f-30d2-46b3-be35-8162a8ceb09f)


😢

**Comment by brianzinn** [comment]
you have something like:
```
const cavity_ref_temp = useRef();
```

Can you change your timeout to:
```
setTimeout(() => {
  console.log('cavite_ref_temp', cavity_ref_temp.current)
  setCavityBlockLoaded(true);
}...);
```

I think you will see that the "rootMesh", which is the "current" is a transform node.  You need to get the mesh you are after from the children of that transform node.  Babylon.js creates that root node and parents your mesh(es) to it.

**Comment by brianzinn** [comment]
if you upload your glb here:
https://sandbox.babylonjs.com/

then open the inspector - when you expand the "nodes" then you will see your meshes.

**Comment by brianzinn** [comment]
There is an official community request that will pave a road to make this easier to address:
https://github.com/BabylonJS/Babylon.js/issues/14567

Closing out from inactivity.  Thank-you for your contribution.
