### ISSUE TITLE
react-babylon as frontend

### ISSUE THREAD

**Issue by j209** [brianzinn/react-babylonjs#298]
hi
is it possible using react-babylon as frontend of a 3d intractive web app that use django as backend?

**Comment by saidmoya12** [comment]
Yes! you can use like url instance npm module or do an integration with webpack

https://stackoverflow.com/questions/31573410/integration-of-javascript-with-django
https://www.saaspegasus.com/guides/modern-javascript-for-django-developers/integrating-javascript-pipeline/

**Comment by brianzinn** [comment]
no limitations at all on backends.  you just need to serve the assets.
