### ISSUE TITLE
[ERROR] Could not resolve "@babylonjs/core/Cameras/VR/webVRCamera.js" deprecated

### ISSUE THREAD

**Issue by saidmoya12** [brianzinn/react-babylonjs#299]
webVRCamera has been deprecated
https://doc.babylonjs.com/features/featuresDeepDive/cameras/webVRCamera

So to upgrade @babylonjs/core throw the following error

```diff
- [ERROR] Could not resolve "@babylonjs/core/Cameras/VR/webVRCamera.js"
```
```
 node_modules/react-babylonjs/dist/react-babylonjs.js:1:4026:
      1 │ ... ne}from"@babylonjs/core/Cameras/VR/webVRCamera.js"
 ```

Please upgrade to webxr camera
https://doc.babylonjs.com/features/featuresDeepDive/webXR/webXRCamera

Thanks!

**Comment by brianzinn** [comment]
thanks @saidmoya12 - i'll build a new version.  need to remove 1 demo - it's been legacy for quite a while.  sorry i had missed this issue opening.

**Comment by brianzinn** [comment]
sorry.  didn't mean to close.  having some trouble deploying new version - will try to sort it out tomorrow.  cheers.

**Comment by brianzinn** [comment]
Should be fixed on latest version.  I tested on codesandbox.  Thanks for reporting.
