### ISSUE TITLE
Add a declarative way to define render loops

### ISSUE THREAD

**Issue by andrewpeterprifer** [brianzinn/react-babylonjs#30]
It seems to me that currently the only way to add a function to execute on every render is to do

```js
function onSceneMount(e) {
  const { canvas, scene } = e

  // Your code here (ie: playground code could go here)...  
  scene.getEngine().runRenderLoop(() => {
      if (scene) {
          scene.render();
      }
  });
}

function NonDeclarative() {
  return (
    <Engine canvasId="sample-canvas">
      <Scene onSceneMount={onSceneMount} />
    </Engine>
  );
}
```

This is problematic not just because it is verbose, but also because this way render loop functions need to be added/changed/cleaned up imperatively by hand. I think a better way would be to control the lifecycle of render loops declaratively through the use of react hooks.

I propose adding a `useRenderLoop()` hook to the react-babylonjs API which would look something like this:
```js
function Declarative() {
  useRenderLoop((engine /* or properties relevant to rendering like deltaTime */) => {
    // ...
  })

  return (
    <>
    // ...
    </>
  );
}
```

 This would make adding render loops much less verbose, but more importantly it would allow us to declaratively manage replacing render loops on change or cleaning them up when a component unmounts.

**Comment by brianzinn** [comment]
good idea. i just started, but now want to rewrite the `Scene` and `Engine` as functional components with hooks...  that's not going to happen for 3 weeks as I'm super busy.

here is what the definition will look like I think:
```
export type OnFrameRenderFn = (eventData: Scene, eventState: EventState) => void

export function useRenderLoop(callback: OnFrameRenderFn, mask?: number, insertFirst?: b
oolean, callOnce?: boolean): void {
}
```

I think I'll use scene.onBeforeRenderObservable and `useEffect` to remove the observable.  Main thing that I need to fix is for the Scene.Provider to bubble up the change with the new context once the scene is ready (canvas loaded and scene created).  `useContext(BabylonJSContext)` right now is just `{scene:null, ...}` with initial state.  That will be great to add and actually I really want to demo that using either PixiJS overlay or the ECS (ecsy from Mozilla) and custom render methods.  Thanks for the idea - will be dropped into next update.

**Comment by brianzinn** [comment]
made a branch: `https://github.com/brianzinn/react-babylonjs/tree/render-hook`

Sample using deltatime (spinning box):
```jsx
const RotatingBoxScene = (props) => {
  const boxRef = useRef(null);

  useBeforeRender((scene) => {
    if (boxRef.current) {
      var deltaTimeInMillis = scene.getEngine().getDeltaTime();

      const rpm = props.rpm || 10;
      boxRef.current.hostInstance.rotation.y += ((rpm / 60) * Math.PI * 2 * (deltaTimeInMillis / 1000));
    }
  })

  return (
    <>
      <freeCamera name='camera1' position={new Vector3(0, 5, -10)} setTarget={[Vector3.Zero()]} />
      <hemisphericLight name='light1' intensity={0.7} direction={Vector3.Up()} />
      <box ref={boxRef} name='box1' size={2} position={new Vector3(0, 1, 0)}>
        <standardMaterial diffuseColor={Color3.Red()} specularColor={Color3.Black()} />
      </box>
      <ground name='ground1' width={6} height={6} subdivisions={2} />
    </>
  )
}

const RenderHooks = (props, context) => {
  return (
    <Engine antialias adaptToDeviceRatio canvasId='babylonJS' >
      <Scene>
        <RotatingBoxScene rpm={20} />
      </Scene>
    </Engine>
  )
}
```

if you run:
`yarn build`
`yarn storybook`

and navigate to "Physics and Hooks" -> "Render Hooks" hopefully that will work for you.  I haven't tested replacing the render loop, but I think the hooks should handle that (and the cleanup is automatic).  If the spinning doubles in speed, for example, we would know the loop was executing twice.

Check out that branch if you have any time, but otherwise I will merge in after some more testing.  Sorry it took so long - was on vacation for 3 weeks and then catching up at work! :)

ps: I like your name more `useRenderLoop`, but wanted to capture that it happens *before* render, so can easily add an After Render observable if needed and be backwards compatible.  Maybe I should add `Loop` back, though?

**Comment by andrewpeterprifer** [comment]
Hi, looks awesome, hope you enjoyed your vacation! Haha I don't think we can come up with a name for it that is specific and makes perfect sense at the same time without it becoming a mouthful. I'd keep it `useBeforeRender`, `useBeforeRenderLoop` kinda suggests that it happens before the entire loop.

**Comment by brianzinn** [comment]
Thanks.  Closing issue as it is merged.  I'll do a bit more testing and then publish.  Thanks for the great idea.
