### ISSUE TITLE
how to access child component via ref ? 

### ISSUE THREAD

**Issue by lawplatform** [brianzinn/react-babylonjs#303]
I made child component <monekey> which is load glb file 

```
const monkey=()=>{
<Model name="monkey" /> //loaded glb
}

```
and for the parent component, I want to get access using ref 

```
<scene>
    <monkey ref={Refvalue}/>
</scene>

```
but log say ref is not intrinct, so I use forwardRaf 
`const monkey: FC<ByMonkeyProps> = forwardRef((props, ref: ForwardedRef<HTMLDivElement>) => {}
`
but dosen't work at all

how to control child compoent (model, camera, light.. etc) in the parent component ?

**Comment by brianzinn** [comment]
would this PR fix for you? https://github.com/brianzinn/react-babylonjs/pull/270
Not really clear what you are trying to get a ref to - the forward ref for a DOM element.

**Comment by lawplatform** [comment]
![usinref](https://github.com/brianzinn/react-babylonjs/assets/140143233/e38a8432-d798-4c15-af73-49469a804e26)

try to @ts-ignore or forwardRef 
it make no error message but fail to get ref.current (even I passed) 

I just want to control interection in the parent view not the seperate object file 

or.. is it better to access child component property 
using 
`const scene = useScene()`
?

**Comment by brianzinn** [comment]
hi @lawplatform that PR should work - I will merge it once the conflicts in the PR are resolved.  I have tested and it works like this:
```tsx
const MyComponent = () => {
   const modelRef = useRef<Nullable<AbstractMesh>>(null);

   const checkModel = () => {
    console.log('model ref:', modelRef.current);
    if(modelRef.current) {
      modelRef.current.rotation.y += (Math.PI / 32);
    }
  }
  
  return (
     <button onClick={checkModel}>rotate model</button>
     <Engine ...>
      <Scene ...>
         ... lights/etc
         <Suspense ...>
            <Model ref={modelRef} />
         </Suspense>
      </Scene>
    </Engine>
  )
}
```

**Comment by brianzinn** [comment]
also, I didn't need a ts-ignore using `AbstractMesh | null`.

**Comment by brianzinn** [comment]
yes, it will work the same the example above once the PR is merged.

**Comment by lawplatform** [comment]
thanks :) have a nice day!
