### ISSUE TITLE
Can't resolve '@babylonjs/core/Engines/Extensions/engine.views.js'

### ISSUE THREAD

**Issue by scriptex** [brianzinn/react-babylonjs#321]
Recent updates to the core library (`@babylonjs/core`) started triggering this error. 

I am trying to update the core library to v7.9.0 (or any version above v7.8.0 FWIW) and it keeps throwing this error. 

After checking in the available files in `node_modules` I see that the mentioned file exists in version v7.8.0 but is no longer available in future versions.

**Comment by brianzinn** [comment]
thank-you for reporting.  i will check the downstream and perhaps make a PR there or release here.  this doesn't happen very often due to their backwards compatibility

**Comment by scriptex** [comment]
Thank you! I checked the latest core library releases and their changelogs and couldn't find anything related to this change. It might not be a breaking change for the core lib but unfortunately it triggers issues in libs built on top...

**Comment by brianzinn** [comment]
thanks @scriptex - I will be doing a PR to core library for them to maintain backwards compatibility.  I should PR today hopefully and then it will drop in next release.

**Comment by brianzinn** [comment]
https://github.com/BabylonJS/Babylon.js/pull/15154

**Comment by scriptex** [comment]
They merged the linked PR so I guess it will be released soon.

**Comment by brianzinn** [comment]
@coolbeatz71 - can’t do much except wait. The new core lib will be backwards compatible. I don’t know if there is an official release schedule. I will drop a new release after with some new features, so I’m waiting as well. Cheers.

**Comment by scriptex** [comment]
They've releases v7.10.0 which fixes this issue 🎉 ! Thanks for the quick turnaround, I am closing the issue 😄
