### ISSUE TITLE
useHover example is not working properly

### ISSUE THREAD

**Issue by xzwang2005** [brianzinn/react-babylonjs#326]
Hovering over GUI or the ball doesn't trigger the event. But need to offset to a location left to the objects. This is only a problem on the [help page](https://brianzinn.github.io/react-babylonjs/examples/hooks/hover/), it works fine in Sandbox.

See attache video.

https://github.com/user-attachments/assets/18840382-18e9-4577-a3e9-a1aac745d365

**Comment by brianzinn** [comment]
Thanks for the comment. I’ll have a look when I get to a computer. Sometimes a resize doesn’t fire. Hopefully nothing with pixel ratios, etc.   cheers

**Comment by brianzinn** [comment]
I can reproduce, but with a much smaller offset.  Seems if I resize the entire window - the canvas gets much larger.  Possible not the entire size is reported.  I wonder if this was introduced in the newer versions of babylon.js - they are running on different versions of babylon.js....

**Comment by ViktorZhurbin** [comment]
I can't seem to reproduce it now, with the new docs update. Might have fixed itself 😆 

@xzwang2005 Could you check it once again?

**Comment by xzwang2005** [comment]
yep, it's fixed!  Thanks~

**Comment by xzwang2005** [comment]
Resolved
