### ISSUE TITLE
Context not available in components embedded in <Scene>

### ISSUE THREAD

**Issue by xzwang2005** [brianzinn/react-babylonjs#330]
hi,

I've created this example to demonstrate the issue: https://codesandbox.io/p/sandbox/4ggvtz

`useMyContext` is a hook to retrieve the context of a custom type `MyWorld` defined in context.tsx

The `App` component wraps everything inside `MyContextProvider`, the first component `Abutton` retrieves the context correctly and show its `name` property.

However, `MyMesh` is not able to get the context with the hook. I have to wrap everything under `<Scene>` with another `MyContextProvider` to pass the context, see the attached images. Is it expected?
<img width="975" alt="Screenshot 2024-12-27 at 12 14 20 AM" src="https://github.com/user-attachments/assets/0ea5e742-e060-45a7-bfbf-6c812e2ffabf" />

**Comment by brianzinn** [comment]
Yes, sorry. That is a limitation of renderers. You can make your own bridge though. There’s more details and and code example here:

https://brianzinn.github.io/react-babylonjs/examples/basic/context-bridge/

Re-open if you need more assistance. Cheers
