### ISSUE TITLE
How to redraw the scene in response to context change?

### ISSUE THREAD

**Issue by xzwang2005** [brianzinn/react-babylonjs#331]
hi Brian,

This is a follow up for my [last question](https://github.com/brianzinn/react-babylonjs/issues/330#issue-2760565313).

I have updated the [sandbox](https://codesandbox.io/p/sandbox/4ggvtz) so that the same context is passed to `Abutton` and `MyMesh`. The goal is that once `Abutton` updates the context(i.e., change the size of the box), `MyMesh` will redraw the box in the scene with the new size.

However, the actual behavior now is that MyMesh keeps adding boxes with the new size; also the texture seems off, wireframe={true} is not honored, the newly added boxes are solid. See the attached video.

The console log shows that `MyMesh` did received the updated context, but why is the box not updated?

https://github.com/user-attachments/assets/f871a7ee-cbc2-4355-b9ff-eb740b9cff2b

**Comment by brianzinn** [comment]
Can you try with “key” being the constructor args? That should solve your issue and the reconciler will handle the rest.   Kinda like this:

https://github.com/brianzinn/babylonjs-directed-graph/blob/master/src/App.tsx

**Comment by xzwang2005** [comment]
The mesh is updating now ([sandbox](https://codesandbox.io/p/sandbox/babylonjs-context-4ggvtz)) with the pattern from [this example](https://brianzinn.github.io/react-babylonjs/examples/basic/from-instance/index).

However, the material properties are not preserved. I've set the material to `wireframe={true}`, it applies correctly initially, but not after the context changed.

https://github.com/user-attachments/assets/7a04ebd3-396a-4573-bf5e-c92d693509f3

**Comment by brianzinn** [comment]
Is there a reason you need to do it that way?  What about this?
```jsx
const MyMesh = () => {
  const { world } = useMyContext();
  console.log(` > Rendering Mymesh: ${world.boxes[0].width}`);

  return (
    <box
      size={world.boxes[0].width}
      key={`${world.boxes[0].width}`}
      name="mesh"
    >
      <standardMaterial name="mat" wireframe={true} />
    </box>
  );
};
```

I'd need to dig through the code, but the underlying reason I believe is that "fromInstance" is that the lifecycle of the material is that it won't be re-applied when it's parent is updated.  I think it's just lost.  I was actually working at one point to have constructor arguments re-build the scene, but it's quite complex.  Some properties can be changed at run-time.  The thing about the Mesh Builder functions is that they aren't really an updateable object in that the original "builder" arguments are not updateable at run-time, so you can trick the reconciler into re-creating the object.  Let me know if that works - maybe you have simplified something more complex to be easy to share in a sandbox?

**Comment by xzwang2005** [comment]
I'm working on a CSG based modeling app (i.e., simplified version of Blender). User inputs a list of instructions to `cut` the geometry.
At the high level, this list of the instructions is the `state`. When user edit the list, the result is reflected in the canvas.
Another requirement is that user shall be able to specify parameters by selecting vertices in the model. E.g., when user select a vertex, some calculation will be done and update the state.

Are these possible with BabylonJS?

**Comment by brianzinn** [comment]
Yes, I think you may end up with some of the trickery you have there.  Here is an example with CSG:
https://brianzinn.github.io/react-babylonjs/examples/basic/extrude-csg/index

There is a CSG2 I have been meaning to test out - it uses Manifold via wasm.  From the generated mesh you can select vertices/edges.  To get more into that might be good to ask in main forum.

**Comment by xzwang2005** [comment]
It seems that without `<mesh>` tag but return an empty fragment, the sandbox works as before. I might get away with imperative code.

**Comment by brianzinn** [comment]
Then you can just return null. The nice thing about <mesh> is you can pass props through, if needed. You only need to track object instances. Glad you got it figured out!
