### ISSUE TITLE
How to get the loading progress of the Model element?

### ISSUE THREAD

**Issue by vimcaw** [brianzinn/react-babylonjs#37]
Hi Brian, thank your great work, which helps me a lot. I'm a newcomer of babylon.js, same as `README.md`, I use the `Model` element to load a model, but wonder how to get the loading progress of the model.

I know, in native babylon.js, 
```js
BABYLON.SceneLoader.Load(Scenename, name.babylon, engine, function1, function2);
```
it's possible to get loading progress by `function2` arguments, but in the `Model` element, how should I do?
```js
<Model
  rotation={new Vector3(0, this.state.modelRotationY, 0)} position={new Vector3(0, 1, 0)}
  rootUrl={`${baseUrl}BoomBox/glTF/`} sceneFilename="BoomBox.gltf"
  scaling={new Vector3(20, 20, 20)}
/>
```

**Comment by brianzinn** [comment]
You can get the loading progress by passing in a prop for `onLoadProgress`.  Here is an example:
https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/ScaledModelWithProgress.js

For that example with a `.gltf` you will normally be OK (I think it uses bytebuffer bytelength).  I think other model types (ie: OBJ with MTL or .gltf with .bin) will be inaccurate.  Also, I think the server needs to support `content-length` for single file ones.  Give it a try and see how it works out for you.  You can see in my example that I have estimatedFileLength as a prop and you can use something like that when you know the size of the model.

Here is a live demo of model loading progress - you can see for gltf that it's very accurate:
https://brianzinn.github.io/react-babylonjs/?path=/story/babylon-basic--model

**Comment by brianzinn** [comment]
I should have some time next week to look at issue 35 finally :). I'd really like to have a declarative CSG working!  I find it really useful.

**Comment by vimcaw** [comment]
Thanks! It works perfectly, and I can learn a lot from Storybook.
