### ISSUE TITLE
AdvancedDynamicTexture.CreateFullscreenUI(). How can I develop this feature in a better way?

### ISSUE THREAD

**Issue by hookex** [brianzinn/react-babylonjs#40]
This API needs to be used. How Can I encapsulate this static function? 
I'd like to hear your advice.

**Comment by brianzinn** [comment]
The easiest way I can think of right now is to add a new custom property `CreateFullscreenUI` and then:

Update here https://github.com/brianzinn/react-babylonjs/blob/master/src/customComponents/AdvancedDynamicTextureLifecycleListener.ts#L54
With:
```javascript
} else if(props.CreateFullscreenUI === true ) {
   // copy this code:
  // https://github.com/BabylonJS/Babylon.js/blob/eff6a21709f9c77961fcf6d5965df98a53215fbe/gui/src/2D/advancedDynamicTexture.ts#L921
}
```

Generating code from static methods to declarative as it is now was a quick fix and needs to be kept in sync manually.  It would be safer to generate from the static methods like is done for MeshBuilder!  Then there would be a new component called `FullscreenUI`.

**Comment by hookex** [comment]
I am trying to create a new Component <FullScreenUI/>, it needs a namespace, maybe <ADTFullScreenUI>.

It's namespace prefix and `UI` characters is troublesome.

https://github.com/hookex/react-babylonjs

**Comment by brianzinn** [comment]
Thanks for your PR to add this feature @hookex :)
