### ISSUE TITLE
About react reconciler's commit and removeChild.

### ISSUE THREAD

**Issue by hookex** [brianzinn/react-babylonjs#43]
I have two problems during my development. And want to discuss with you how to resolve it.

## 1. commit to `root container`

Now, the Babylon element will be added to the `scene` in the `createInstance()` method.  So before `prepareForCommit()`. All elements were added to the scene and can be seen.
 I think they should be attached to the scene together at the same time as `ReactDom`.

Below is a bug about it. An animation start in `onCreated()` callback.
Between the element first time seen and animation begin to run, the time intervals for a long time.
Due to so many sync js code must be run after the `onCreated()` method.

```
## Create ui tree process
$$: 456.82421875ms element create:
$$: 1871.689208984375ms element begin animate
[Violation] 'requestAnimationFrame' handler took 152ms
```
```
## update ui tree process
$$: 6537.644287109375ms element create
$$: 6878.276123046875ms element begin animate
[Violation] 'requestAnimationFrame' handler took 65ms
```

## 2. Maybe RemoveChild needs recursion operation. 

Case: some deep children can't be removed.

**Comment by brianzinn** [comment]
That is a very interesting request. The reconciler prepareCommmit feels too late and I hope not needed. BabylonJS scene isn’t created until after the canvas is attached to the DOM. Most of the complexity around the order of creation is due to GUI adding/removing controls in correct order and reconciler creating in a different order.

Are you suggesting we prepare an instruction set of some kind and run it on prepareCommit? I’d like to look at maybe some profiling - can you share a story/example for that and removing with deepRecursion?

Looks like a big time gap in your issue - are you in a tough loop? Surprised to see such a long time interval. Thanks for creating issue.

**Comment by brianzinn** [comment]
Maybe another method like ‘onReady’ for after the sync code has completed (from ‘prepareForConnit()’. I think we could maintain a list and trigger those together or walk the tree (slower?).

**Comment by hookex** [comment]
@brianzinn 

### Well loop
My application is in a good loop, only minor modifications to `react-babylonjs`'.
I'm reading and try to modify the reconciler config file. 


### long time gap between scene seen and  and `useEffect() | onCreated()`
The original problem is long time gap between scene first time scene and `requestAnimationFrame()`. 
There is no perfect method to resolve it now.  I will study it furture.

### removeChildFromContainer()
Its method has bugs and be fixed. 

example:
https://github.com/hookex/react-babylonjs/blob/master/stories/babylonjs/1-basic/toggleMesh.stories.js

I will submit a PR this weekend.

**Comment by brianzinn** [comment]
You can also control the visibility of the canvas with css. Maybe we can add a lifecycle method or callback where you can make visible and add animations?

**Comment by hookex** [comment]
> You can also control the visibility of the canvas with css. Maybe we can add a lifecycle method or callback where you can make visible and add animations?

I will try, thanks.

**Comment by brianzinn** [comment]
I am noticing the startup is slower and I’m losing even webgl context. I’ll do some timing tests against 4.0, but it feels noticeably slower currently.

**Comment by brianzinn** [comment]
Can this issue be closed?  Looks like it was solved in your PR.

**Comment by hookex** [comment]
Sure.
