### ISSUE TITLE
Edges Rendering support

### ISSUE THREAD

**Issue by cheemcheem** [brianzinn/react-babylonjs#54]
Hi Brian, 

Just wanted to say thank you for this repo, it has been really nice to use!

I have an issue with edge rendering in that it doesn't allow me to call `enableEdgesRendering()` on a tiledGround for example. 

When I put the following code in my scene:
```jsx
<tiledGround name={"ground"} 
             onCreated={g => g.enableEdgesRendering()} 
             edgesWidth={8.0} 
             edgesColor={Color4.FromInts(0,0,0,0)}
             xmax={60} xmin={-60} zmax={60} zmin={-60}/>
```
I get the following console error in `react-reconciler.development.js?c996:1824`: `Uncaught EdgesRenderer needs to be imported before as it contains a side-effect required by your code.` 

The only way around this that i've found is to manually add the tiled ground to the scene using raw babylon, and call `enableEdgesRendering()` etc on that object.

Are there any plans to support this declaratively in future? Or is there a way for me to extend the existing tiledGround component myself?

Thanks,
Kathan

**Comment by brianzinn** [comment]
The reason that you get that error is that the edges rendering is patched to the Mesh as an ES6 side-effect.  You need to add an import to get the side-effect like this:
```javascript
import '@babylonjs/core/Rendering/edgesRenderer'
```
You can see the code here where the method `enableEdgesRendering` is added (this code is called when you import with side-effects).
https://github.com/BabylonJS/Babylon.js/blob/42e54febe1c8307623a6b984ecef40cf9e83518e/src/Rendering/edgesRenderer.ts#L35

I tested it out on a working example here:
https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/1-basic/edgesRendering.stories.js

What I did with some other methods was to add them to the reconciler, so if I did that then you could for example do:
```jsx
<box name="box1" enableEdgesRendering={[]} edgesWidth={3} />
```

If you think that is a useful feature then I can add it, but you would still need to do the import for side-effects.  Right now the reconciler doesn't know about that method, so it wouldn't call it on your Mesh.

**Comment by cheemcheem** [comment]
Thank you very much for getting back to me!

I tried to use the code you added here: https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/1-basic/edgesRendering.stories.js, but I still got the same exception.

I'm using webpack to bundle my code, do you think the issue could be in my config?

Thank you,
Kathan

**Comment by brianzinn** [comment]
It looks like you are treeshaking and missing the direct import.  See this issue:
https://github.com/BabylonJS/Babylon.js/issues/6257
Do you see in your webpack output the AbstractMesh prototype patching?  You should have it being called on the class itself, but you need to evaluate via an import with side-effects to have the AbstractMesh prototype method patched (the default behavior otherwise calls this):
https://github.com/BabylonJS/Babylon.js/blob/master/src/Misc/devTools.ts#L4
Does it run on dev mode and not on build?

**Comment by brianzinn** [comment]
@cheemcheem can you try `npm i react-babylonjs@2.1.0-alpha.0`?

**Comment by cheemcheem** [comment]
Chaning the version of react-babylonjs from 2.0.5 to 2.1.0-alpha.0 lets me run your example! 

The string "AbstractMesh.prototype.enableEdgesRendering" exists in my bundled output file when using both react-babylnjs 2.0.5 and 2.1.0-alpha.0.

I've been using 'development' as my webpack mode but I tried on 'production' with 2.0.5 and it still failed in the same way.

**Comment by brianzinn** [comment]
So, it’s working on the 2.1 alpha for both dev and production (ie: we can close issue)?

**Comment by cheemcheem** [comment]
Yup should be fine to close, just tested production on the alpha version too and it works! 

Thank you for your help!
