### ISSUE TITLE
[proposal]hooks

### ISSUE THREAD

**Issue by hookex** [brianzinn/react-babylonjs#55]
@brianzinn 
Do you think we need to add some other hooks?

For example:

#### useClick
`useClick(onClick: Function<event>): [ref]`

https://github.com/hookex/bviz/blob/master/src/hooks.ts

#### useHover
`useHover(over: Function<event>, out: Function<event>): [ref, isHovering]`

https://github.com/hookex/bviz/blob/master/src/hooks.ts

**Comment by brianzinn** [comment]
Most definitely - great use of action manager and very useful!  The only thing I don't know is if we should be returning a method to de-register before the mesh disposes (like `useBeforeRender` hook does).  Hopefully babylonjs takes care of that automatically when the mesh is removed from the scene.

**Comment by brianzinn** [comment]
When the mesh is disposed (which happens when it is removed) the action manager is disposed:
https://github.com/BabylonJS/Babylon.js/blob/master/src/Meshes/abstractMesh.ts#L1603

So, under normal conditions likely wouldn't need this.  One issue may arise when referencing a mesh in parent hierarchy (like a forwardRef), as it will keep registering actions if the effect is re-created.  Does this look right?
```javascript
useEffect(() => {
        if (ref.current) {
            // what you have now...
            const registeredAction: Nullable<IAction> = mesh.actionManager.registerAction(
               // ...
            );

            return () => {
                // called when component is unmounted?
                mesh.actionManager!.unregisterAction(registeredAction!)
            }
        }
    }, [ref.current])
}
```

**Comment by brianzinn** [comment]
Also, I will add it separately, but it needs a guard clause - can check the metadata.  GUI have a different hover:
```
onPointerEnterObservable.add(() => { /* ... */ }
```

If you make a PR I will accept with or without those extra changes.  Thanks Hooke!

**Comment by hookex** [comment]
Thanks for your remind.  I will add this code.
Over the next few days, I will integrate my application with spring and event hooks, then submit PR.
