### ISSUE TITLE
Attach 2D UI element to Mesh

### ISSUE THREAD

**Issue by j-te** [brianzinn/react-babylonjs#62]
I want to achieve this as per the official docs:
https://www.babylonjs-playground.com/#XCPP9Y#16

Normally you would use `linkWithMesh()` to link the rectangle with the mesh. How would I achieve this? I see there may be a prop `attachToMeshesByName`?

```js
<Scene>
  <adtFullscreenUi name="ui1">
    <freeCamera name="camera1" position={new Vector3(0, 2, -10)} target={Vector3.Zero()} />
    <sphere name="sphere1" diameter={2} segments={4} position={new Vector3(2, 1, 0)} />

    <rectangle
      key={"label"}
      name={"label for Sphere"}
      background={"black"}
      height="30px"
      alpha={0.5}
      width="100px"
      cornerRadius={20}
      thickness={1}
      linkOffsetY={30}
      top={"10%"}
      attachToMeshesByName={"sphere1"}
    >
      <textBlock name={`sphere-text`} text="Sphere" color="White" />
    </rectangle>

  </adtFullscreenUi>
</Scene>
```

**Comment by brianzinn** [comment]
That's a good feature request `linkToMeshByName` - the `attachToMeshesByName` is for attaching a material to multiple meshes.

I do have a story with examples calling `linkWithMesh` imperatively - official demo here:
https://www.babylonjs-playground.com/#3VMTI9#0

You can see it is partially implemented here (storybook):
https://github.com/brianzinn/react-babylonjs/blob/master/stories/babylonjs/GUI/gui.stories.js#L85

Live demo here:
https://brianzinn.github.io/react-babylonjs/?path=/story/gui--gui-full-screen

That demo has recent features, but never took it to be fully declarative.  So, to answer your question there is no declarative way to do so currently.  If you want to propose a declarative way then I could add it.  When linking by name there is generally an observable added for when meshes are added to the scene.

**Comment by brianzinn** [comment]
closing from inactivity.  kindly re-open if this is a desired feature for you.  thanks for the issue - sorry it never got any traction.  cheers.
