### ISSUE TITLE
Is there any easy way to support new custom element: <instance/> & <primitive/>.

### ISSUE THREAD

**Issue by hookex** [brianzinn/react-babylonjs#64]
Hi Brain:

I've been trying to support `<primitive/>` element, but I find it difficult to support a custom new element. Do you have any suggestions?

#### about `<primitive/>`

The component is like this.

https://github.com/react-spring/react-three-fiber#putting-already-existing-objects-into-the-scene-graph

I use `useLoader()` and `<primitive/>`  to render gltf model.

**Comment by brianzinn** [comment]
if you want to use something like that then it would need to be supported by the reconciler.  it raises a very interesting issue as it won't know how to assign props handlers for updates - this may require some major rework, but looks very useful.  What are you assigning to the primitive?

Can you show me how you are using `useLoader()` - I think that would be a good way to use suspend - just added support for that recently.

**Comment by hookex** [comment]
This is the demos.

> What are you assigning to the primitive?

https://github.com/hookex/react-babylonjs/blob/master/stories/babylonjs/Basic/primitive.stories.js

> Can you show me how you are using `useLoader()`

`<Model/>` can't properly handle resource preloading and caching. Especially if there are a lot of the same models.

So `useLoader()` and `<primitive/>` is a flexible combination.

https://github.com/hookex/react-babylonjs/blob/master/src/hooks/useLoader.ts

https://github.com/hookex/react-babylonjs/blob/master/stories/babylonjs/Hooks/useLoader.stories.js

**Comment by brianzinn** [comment]
wow - that is very cool!  you look to have tried a few different things in the reconciler - where I was thinking.  I think the issue may be that the object={} is not set on initial load and there is no props handler for it.  You would need a custom handler for primitive to accept the object and parent it to your transformNode for example.  I think this is a clear example where extending in this unexpected way may mean that the reconciler and props handling should be more generic.  ie: how to know that position can be applied?

What would maybe work is something like this:
```jsx
function WithPrimitive(props) {
  const scene = useBabylonScene();

  const mesh = useMemo(() => {
    return Mesh.CreateSphere('sphere', 16, 2);
  }, [])


  return <transformNode position={new Vector3(2, 0, 0)}>
    <sphere waitForLoad={mesh} position={new Vector3(0, 2, 0)} />
  </transformNode>
}
```

So, it would hopefully work with Suspense.  I wonder if that is a good approach - I have to think more if something like this would work well in your scenario and other scenarios.  I will work on this on Saturday!! :)  Let me know if you have other ideas as well.

**Comment by hookex** [comment]
I agree with your idea, It will have direct props hint.
So we can render GlTF model by using the below way.

```
function GlTF() {
    const mesh = useLoader('xxx');
    return <node object={mesh}  position={new Vector(0, 0, 0)}/>
}
```

My application renders thousands of models of the same GlTF model.
By using the `<GlTF/>` like component, I solved the problem of reloading resources.
But the react reconciler has a lot of pressure to calculate thousands of components.
I'm going to use `<instances data = {position}, {position}]/>` to optimize Performance issues with large scenario.

**Comment by brianzinn** [comment]
Hi @hookex ,

I think this is fixed in the latest version.  There is a new property `fromInstance`.  It should work for a typical scenario like this:
```
const BoxModel = ({ position }) => {
    const url = 'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Box/glTF/Box.gltf';
    const [loaded, { meshes }] = useLoader(url);

    if (loaded === false) {
        return null;
    }

    return <mesh fromInstance={meshes[1]} position={position}/>;
}
```

The advantage over primitive is the JSX code completion and syntax highlighting.  Is there anything missing here that you need?

**Comment by brianzinn** [comment]
hi @hookex - with so much changed since this issue I'm going to mark closed.  There is also an `<instancedMesh source={..} />` added and new hooks for loading.  There is likely a way to improve performance in my loop for property differences - I would want to have solid way to benchmark as a starting point and then could compare improvements.  Going to close as you have a solution and there are new options since this issue was created.  Thanks for all of your great contributions and questions!
