### ISSUE TITLE
How do you dispose of the engine?

### ISSUE THREAD

**Issue by PaulRyan97** [brianzinn/react-babylonjs#65]
Hi,

I'm looking for a way to dispose of the engine once my component containing it unmounts. I thought this might be done by default but it looks like it's not. Is there anyway to access the engine object from say a useEffect hook in the component the engine is declared in?

**Comment by brianzinn** [comment]
Good catch - above commit should resolve and dispose automatically.  You could dispose yourself by getting the Engine from the context and something like a `useEffect` returning `() => engine.dispose();`  I'll try to get an NPM out soon - there are some other pending changes.  That code would itself need to be contained inside the Engine JSX markup to have the engine available on the context.  HTH

**Comment by PaulRyan97** [comment]
> You could dispose yourself by getting the Engine from the context and something like a useEffect returning () => engine.dispose();

I had tried something like that but I seem to keep getting a null value back for the Engine object. Do you have an example of how you would see this workaround working?

**Comment by brianzinn** [comment]
You can do scene.getEngine() or get engine from context before Scene component (inside Engine). Inside Scene component is where the reconciler overwrites the context.  It’s a bit tricky how React resets context Inside the reconciler.  Engine will be disposed automatically when the Engine component unmounts in the code fix :)

**Comment by brianzinn** [comment]
Should be fixed in `react-babylonjs@2.2.1` - please re-open if you have any more questions or this is not resolved for you.  Cheers.
