### ISSUE TITLE
Can't get Typescript and useBeforeRender hook to work together

### ISSUE THREAD

**Issue by FrederikP** [brianzinn/react-babylonjs#67]
Hi,
is there any example of how to use `useBeforeRender` and typescript?
I haven't been able to get it to work. It just never calls the callback. During debugging I noticed that `const {scene, sceneReady } = useContext(SceneContext);` always returns `{null, false}` for me. So no wonder the callback is not called.

What's weird: Using the contextlogger component from the example I can see that `useContext(SceneContext)` returns the scene and sceneReady is true. (Edit: Oh, maybe the issue is that my component contains divs, engine and scene tag and it needs to be below context for the context to return something? I'll revisit)

I took a look at https://github.com/brianzinn/react-babylonjs/blob/9228ac840b5ede903f493d3d660ef941fd93de36/stories/babylonjs/Hooks/hooks.stories.js . It works locally for me. I tried to copy as much as I can (I had to to some casting to make the ReactScene stuff (`const Scene = withScene(ReactScene)`) not throw any typing errors. Maybe that's where the main issue is?

I would greatly appreciate any pointers/help. I am sorry if this is the wrong place to ask something like that, but maybe you can classify it as a "documentation issue".

**Comment by FrederikP** [comment]
Okay the reason was, that the component itself needs to be enclosed by the scene for the context to work. Makes sense...

**Comment by brianzinn** [comment]
Thank for posting your question and answer.  I will be updating the readme to be more of a tutorial instead of examples and will be highlighting that.  The way the reconciler creates it's own context will be explained.
