### ISSUE TITLE
updating lines points does not update the view

### ISSUE THREAD

**Issue by rikkertkoppes** [brianzinn/react-babylonjs#68]
Just starting with babylon and react-babylonjs, so bear with me.

I have a component that gets a path as a prop (from redux). I'd like to draw this path and update it as the prop changes:

```typescript
const TestPathPres = ({ path }: any) => {
    let points = [];
    for (let o = 0; o < path.length; o += 1) {
        let p = path.getPointAt(o);
        points.push(new Vector3(p.x, 0.15, -p.y));
    }

    console.log("rendering track", points, path);
    return <lines name="track" points={points}/>;
};
```

When the path updates, I see the updated points array in the console, so the redux integration and rerendering seem to work just fine.

However, the line does not update in the view. Tried adding the `updatable` flag, but no results either.

When I, for example, render a sphere on the first point of the path, updating the path does move the sphere to a new position

**Comment by brianzinn** [comment]
You've hit upon one of the intricacies of how props flow to meshes.  You would be able to see which properties are not "updatable" by looking at MeshBuilder class.
https://doc.babylonjs.com/api/classes/babylon.meshbuilder#createlines

You can see that `points` is a constructor parameter.  For you to set `updatable` means that you could manipulate the mesh vertices/points after creation and that the mesh itself is updatable.  The properties that are updatable from the react-babylonjs world are all of the properties on the `Mesh` class, such as position, scale, etc..  As a counter example try to update the `diameter` of your sphere.

I had this issue when I was building tracks using Ribbons and changing "paths", which were arrows pointing from one 3D model to another.  The easiest way was to trick React into creating a new object is by setting the `key` property of your `<lines key={`track-${version}`} name="track" points={points} />`.  It is inefficient for me to do an array comparison every time that any prop changes, but I am open to making fundamental changes to support.  Here is a demo of rebuilding by changing keys on versions - the arrows use an array of points and adding buildings will move the arrows:
https://brianzinn.github.io/babylonjs-directed-graph/

Does that work for you to change the `key` when your `points` update?

**Comment by hookex** [comment]
> The easiest way was to trick React into creating a new object is by setting the `key` property like this:

Nice way!

**Comment by brianzinn** [comment]
Going to close this as there is a workaround.  If you are interested in a proposal for re-using constructor args as props then please re-open and can investigate further.  The main issue is re-attaching all behaviours (ie: attached materials, shadows, physics, when removing and re-adding meshes to the Scene).
