### ISSUE TITLE
react-spring/animated no work with last update

### ISSUE THREAD

**Issue by saidmoya12** [brianzinn/react-babylonjs#69]
Good afternoon

The latest release of react-spring/animated no work

Error with react-spring/animated

`Attempted import error: 'extendAnimated' is not exported from '@react-spring/animated' (imported as '$r').`

It's possible upgrait it to animated instance extendAnimated

**Comment by brianzinn** [comment]
Are you on the beta? I think we need to remove this dependency. It was my mistake as I thought it would be a peer dependency that could be ignored.  What version is in your package.json?

**Comment by davydka** [comment]
Getting a `react-spring` error as well.

`Module not found: Can't resolve '@react-spring/animated'`

**Comment by brianzinn** [comment]
I'm going to move the `react-spring` into a separate library.  In the meantime, please drop back to v2.1
```
npm i react-babylonjs@2.1.0
```

```
yarn add react-babylonjs@2.1.0
```

Their latest RC changed, but I didn't want it as a required dependency.  Thanks for bringing up.

**Comment by brianzinn** [comment]
Fixed in `react-babylonjs@2.2.1`.  The `react-spring` integration has been moved to https://github.com/hookex/react-babylon-spring/ thanks to @hookex 🎉
