### ISSUE TITLE
question

### ISSUE THREAD

**Issue by sylvaincordiere** [brianzinn/react-babylonjs#7]
Hi
I have a question about react-babylon component : is it possible to convert a 2d line in 3d wall like ExtrudeBufferGeometry in three.js which extrudes a 2D shape to a 3D geometry and I think the link is broken : https://brianzinn.github.io/react-babylonjs/

**Comment by sylvaincordiere** [comment]
Thanks for your help Brian
I wonder if I can do it in a dynamic way I mean with mouse event handler using react babylon 2D Controls like grid and line. The idea is to draw lines 
In pure javascript using canvas it give something like that : https://codepen.io/anon/pen/zMQVzE.
and on button click transform it in 3d.
A picture is worth a thousand words so 
![2d](https://user-images.githubusercontent.com/39384609/49511914-bc1e1c80-f88c-11e8-9426-39227bda0647.png)
![3d](https://user-images.githubusercontent.com/39384609/49511917-be807680-f88c-11e8-8edc-3d937fdb1d76.png)

**Comment by brianzinn** [comment]
You closed the issue while I was building your example.  Basically what I was doing was to track the mesh click events on a plane (to create the `shape` in my example) and the the 4th click would create a rectangle (with specified `depth`).  Glad you got it working.

**Comment by brianzinn** [comment]
Hi Sylvain - I was thinking something like this:
https://playground.babylonjs.com/#BAVKES
I think better than stackoverflow is the official forum - they have a very responsive community:
https://forum.babylonjs.com/
Cheers

**Comment by vimcaw** [comment]
@brianzinn Hi, Brian, I met an error when using ExtrudePolygon, it showed "earcut is not defined", I saw your tip:

> Note that ExtrudePolygon uses Earcut. I broke that link when I made the 1.0.0 release. Thanks for reminding me. You can find many of the links from the page on this github.io page:
brianzinn.github.io/create-react-app-babylonjs

I'm sorry but I can't find the link about Earcut, can you help me?

**Comment by vimcaw** [comment]
@brianzinn I'have solved it, Thanks.
