### ISSUE TITLE
Adding Material/Texture to Model

### ISSUE THREAD

**Issue by azinge** [brianzinn/react-babylonjs#70]
Hi! I'm currently trying to figure out how to use this package to import a few .obj files into my scene with a diffuse texture set at runtime. For normal geometry components I've been able to assign the texture like so:

```JSX
<box name='box'>
    <standardMaterial name={'mat'} >
        <texture assignTo='diffuseTexture' url={'./image.jpg'} />
    </standardMaterial>
</box>
```

When I try this for Models however, it doesn't work and instead just ignores the standard material:
```JSX
<model rootUrl={`./`} sceneFilename='model.obj'>
    <standardMaterial name={'mat'}>
        <texture assignTo='diffuseTexture' url={'./image.jpg'} />
    </standardMaterial>
</model>
```

Is there a possible way of doing this with this package? Thanks!

**Comment by saidmoya12** [comment]
Model isn't a mesh
Used to import a file with many meshes, lights, etc...

So you can use onModelLoaded

```jsx
const onModelLoaded => (loadedModel)=>{
   loadedModel.meshes.forEach(mesh=>{
      mesh.material = yourNonReactMaterial;
   }
}
...
<Model rootUrl={`./`} sceneFilename='model.obj' onModelLoaded={onModelLoaded} >
```

**Comment by brianzinn** [comment]
The model contains an array of meshes.  What I have been working on is an async loader that will work with `Suspense` where you can declaratively assign the meshes (ie: `meshes[0]`) and use a declared material and texture as you have.  In the meantime, what @saidmoya12 is the best way.

**Comment by azinge** [comment]
Awesome, I ended up using @saidmoya12's solution and it works perfectly!

Thanks for taking the time to respond and great work on the package!

**Comment by sstolzenberg** [comment]
> Model isn't a mesh
> Used to import a file with many meshes, lights, etc...
> 
> So you can use onModelLoaded
> 
> ```js
> const onModelLoaded => (loadedModel)=>{
>    loadedModel.meshes.forEach(mesh=>{
>       mesh.material = yourNonReactMaterial;
>    }
> }
> ...
> <Model rootUrl={`./`} sceneFilename='model.obj' onModelLoaded={onModelLoaded} >
> ```

Hello!
I am obviously very new to react-babylonjs:
How I can properly set up "yourNonReactMaterial" in the above context?
I.e. I know that imperatively, this can be done like here:
https://doc.babylonjs.com/divingDeeper/materials/using/materials_introduction
but then, e.g., the scene is defined as "scene" and not in the context of " \<Scene\> ".
Simply leaving out "scene" in
var myMaterial = new BABYLON.StandardMaterial("myMaterial", scene);
gives me an error:
"Cannot read property 'getMaterialByID' of null”
\- so clearly, I don't know what I am doing here :o)

Thanks for your help,
Sebastian

**Comment by brianzinn** [comment]
@sstolzenberg good questions.  Easiest way is to use a hook to get the scene.
```jsx
import { useScene } from 'react-babylonjs';
const scene = useScene(); // must be inside <Scene />

....
     mesh.material = new StandardMaterial('myMaterial', scene);
....
```

if you are doing much more than that (or want more declarative approach and props to update your material) you may consider using the `useSceneLoader` hook itself (instead of the Model component).  There is not much going on in the Model component actually (https://github.com/brianzinn/react-babylonjs/blob/master/src/customComponents/Model.tsx).

If you work from there then you can do a few interesting things.  You can attach to existing materials and textures, but you can also set your own.  I didn't actually  try this - just free typed, but hopefully it helps you.  Please ask another question or open an issue if you have any further questions.  Don't forget to enclose this in a `<Suspense />`!!
```jsx
const ModelWithMaterials = (props) => {
  const {
    rootUrl, sceneFilename, materialEmissiveColor
  } = props;

  const sceneLoaderResults = useSceneLoader(rootUrl, sceneFilename, undefined, {});

  useEffect(() => {
    return () => {
      // console.log('disposing the sceneloader results.')
      sceneLoaderResults.dispose();
    }
  }, []);

  return sceneLoaderResults.meshes.map(mesh => (
    <abstractMesh key={mesh.name} fromInstance={mesh}>
      <standardMaterial emissiveColor={materialEmissiveColor} specularColor={Color3.Black()} />
    </abstractMesh>
 );
}

```
