### ISSUE TITLE
textWrapping prop on textBlock not applied 

### ISSUE THREAD

**Issue by HugoMcPhee** [brianzinn/react-babylonjs#73]
Hi, adding GUI as JSX has made things much simpler , thanks for this library!

I recently tried wrapping text in a textBlock, and found that setting the textWrapping prop doesn't work, but setting textWrapping on the ref directly does

Here's a codesandbox of the issue
https://codesandbox.io/s/textblock-textwrapping-5ymjz?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/5372332/83880111-0cc44d80-a782-11ea-9d77-96e5f72a4fe7.png)

Happy to look into it myself, but not sure where to start, thanks

**Comment by brianzinn** [comment]
I need to fix the generator.  It's because it's an unknown type:
`boolean | BabylonjsGuiTextWrapping`
Let me look into that.  Thanks for bringing up!

**Comment by brianzinn** [comment]
I will update the generator to treat detected enums as primitives for reconciler.  It's because it can be a boolean or "number" (https://github.com/BabylonJS/Babylon.js/blob/master/gui/src/2D/controls/textBlock.ts#L11).
Should have an NPM out in next couple of days :)

**Comment by brianzinn** [comment]
Am trying to get the code to generate based on primitives and treating enums as primitives (and typescript unions of primitives as primitives) by inspecting the typings.  I spent a couple of hours on it twice already... :)  I can do a quick patch, but would rather hold out and do a proper code fix on the generator.  I'm flagging as a bug.

**Comment by HugoMcPhee** [comment]
thanks! :)

**Comment by brianzinn** [comment]
no problem - sorry it took so long.  I was expecting lots of new properties by searching for primitives and enums programatically, but it only added `textWrapping`!! 😄   It's deployed on version 2.2.2.
