### ISSUE TITLE
useRightHandedSystem breaks scene

### ISSUE THREAD

**Issue by TimurAditazz** [brianzinn/react-babylonjs#77]
if I set `useRightHandedSystem` of the `Scene` to `true` then I see nothing after any mouse click or movement. Reproduced with every example I tried

**Comment by brianzinn** [comment]
hi @TimurAditazz  - I think that commit will fix it.  Not sure when next NPM will get out.  I think the issue was that the `useRightHandedSystem` prop was set after the camera was attached.  Then after movement the entire scene would move out of camera frustum.  So, if you declare `<Scene useRightHandedSystem />` with this fix you should be OK, but I believe same issue would pop up if it was something like `<Scene useRightHandedSystem={state.useRightHanded} />` and you switched afterwards...

**Comment by TimurAditazz** [comment]
Thank you, @brianzinn. That is enough for me to set the right hand once.

I am confused that the repo has `Releases: No releases published`. No idea how your release process should work but would be good to have release tags. Also, it is not possible to just refer the repo in my _package.json_ like
`"react-babylonjs": "github:TimurAditazz/react-babylonjs#dist",`
since it only provides `dist` by `files` section which doesn't exist on the `master` branch

**Comment by brianzinn** [comment]
The releases are published on NPM: https://www.npmjs.com/package/react-babylonjs

If you want to refer to your own repo, just run a `yarn build` (that will publish to ./dist), remove `dist` from your `.gitignore` and push that dir to your repo.  I made a decision to not put distributed output in source control.  HTH.

**Comment by TimurAditazz** [comment]
See my repo fork https://github.com/TimurAditazz/react-babylonjs - it has no `dist` submitted but I still can include it in `package.json`. It is not clear why you don't tag releases in the git.

I have issues with building storybook, should I raise a bug with a way to solve?

**Comment by brianzinn** [comment]
Building storybook should work with 3 commands:
```
$ yarn install
$ yarn build
$ yarn storybook
```
If that doesn't work then there could be an issue somewhere.

Glad you figured out how to link to your repo from package.json :)

I've been meaning to add a github action to publish the repo when it is tagged, but just have not had time the last while.

**Comment by brianzinn** [comment]
I'll try to remember to do release tags going forward - I did a test today on the 2.2.2 release (https://github.com/brianzinn/react-babylonjs/releases).  Closing as original issue is fixed as well.
