### ISSUE TITLE
Why are the dependencies from @babylonjs/* not commited?

### ISSUE THREAD

**Issue by kevzettler** [brianzinn/react-babylonjs#78]
This module is missing a lot of dependencies. 

I'm currently seeing:
`Module not found: Can't resolve '@babylonjs/loaders' in '/Users/kevzettler/code/redtrench/node_modules/react-babylonjs/dist'`

I already have
```
    "@babylonjs/core": "^4.1.0",
    "@babylonjs/gui": "^4.1.0",
```

I see in the readme that it says:
> react-babylonjs v2+ relies on the ES6 @babylonjs/* NPMs. If you are want to use the babylonjs NPM then use the last v1.x of react-babylonjs (ie: yarn add react-babylonjs@1.0.3).

I"m not sure what this means. There is no `@babylonjs/*` package on NPM. am I supposed to manually install all the `@babylon/*` namespace packages?

Why are they not commited to the dependencies of this module?

**Comment by brianzinn** [comment]
The loaders is the only other dependency you’ll need. They are not direct dependencies, but ‘peer’ dependencies. This allows you to reference different BabylonJS versions, even new alpha/beta or even linked versions independently with your project.

They are committed as peer dependencies. I agree this could be more explicit - I’ll update the readme. Thanks for your feedback.

**Comment by abishek28007** [comment]
not sure why I need to install all the `@babylon/*`, if I don't require all of them, kind of defeats the purpose of tree shaking

**Comment by brianzinn** [comment]
@abishek28007 - the @babylon/inspector and @babylon/loaders are no longer peer dependencies of v3 (not out yet), but if you did not use them then the tree shaking would prune them from your bundles.  You will need to import the loaders for side-effects in the new version as well.
