### ISSUE TITLE
Drag and drop Resize request

### ISSUE THREAD

**Issue by robbisy** [brianzinn/react-babylonjs#8]
Hi Brain
Thank you for this repo.
I would like to know if you consider adding drag and drop and resize to your component.
This would allow the possibility to resize a component and also to move it more easely.
Like in this demo : https://www.babylonjs.com/demos/dragndrop/

**Comment by brianzinn** [comment]
I'll add a demo of that to this project: https://github.com/brianzinn/create-react-app-babylonjs
I need a week as I'm super busy right now.  Will post an update here when ready - I will not add a component to this library, but will just create one for the demo that can be reused anywhere.  I am trying to restrict this project to BabylonJS objects, so would consider gizmo, but not as per that demo.

**Comment by brianzinn** [comment]
I've added some changes to the NPM on &lt;Scene /&gt;, which allow the demo to be done mostly declaratively:
https://brianzinn.github.io/create-react-app-babylonjs/dragNdrop

Source:
https://github.com/brianzinn/create-react-app-babylonjs/blob/master/src/dragNdrop.js

If you wanted to come up with a completely declarative version, we could work on one.  Perhaps using the HoC that provides Scene via context.  Should be able to get all of that code into a  reusable component as the remaining non-declarative code is just listening to scene pointer events.

**Comment by robbisy** [comment]
Brian I'm getting some strange effect when I moving around scene.
![drag](https://user-images.githubusercontent.com/18592516/50119749-feb00380-0253-11e9-900c-6d63fbc1b4e7.png)
![drop](https://user-images.githubusercontent.com/18592516/50119754-01aaf400-0254-11e9-8811-c2e40068afd6.png)
Can you see the effect on purple object on the first image and on boxes on the second image ?
Do you get the same result when you move around the scene ?
I'm getting these effects on chrome firefox and edge

**Comment by brianzinn** [comment]
Yes, I was getting the same results.  I've updated the project - it was the minZ=0.001 on the camera causing the issue.  I'm not sure if that is a bug.  Let me know if there was anything else.

**Comment by robbisy** [comment]
It's perfect now
Brian are you consider adding scaling option which allow resize on x y z axis like [here](https://doc.babylonjs.com/babylon101/position#scaling)

**Comment by brianzinn** [comment]
Scaling is already implemented.  When you set the scaling on an object the changes are automatically sent through to underlying object.  Have a look at the scrollbars on the loading models:
https://brianzinn.github.io/create-react-app-babylonjs/withModel

The scrollbars are in this control:
https://github.com/brianzinn/create-react-app-babylonjs/blob/master/src/ScaledModelWithProgress.js

You can scale each axis independently:
```jsx
<Box ... scaling={new Vector3(this.state.loadProgress, 1, 1)} />
```
