### ISSUE TITLE
rotationQuaternion does not work

### ISSUE THREAD

**Issue by ecoinomist** [brianzinn/react-babylonjs#80]
The prop `rotation` does not update on meshes, such as `box`, `sphere`, etc., when being passed as `Quaternion`
Example usage: 
```js
<sphere rotation={new Quaternion(0, 0.1, 0, 1)}  /> // only rotates the mesh on initial load, subsequent changes have no effect
```

**Comment by brianzinn** [comment]
I was already aware of that one - was surprised nobody had raised an issue before as I prefer quaternions.

I can fix that at same time as #73 - just have had zero time to work lately on fixing these issues.  I think in your example you meant to put the property `rotationQuaternion`.

**Comment by ecoinomist** [comment]
Yes, I tried `rotationQuaternion` first, but that prop seems to be ignored altogether, with `rotation`, at least it works initially. Would be good to have `rotation` accept Quaternion, as it is the best practice in many 3D engines; especially if you have physics, Babylon even requires a Quaternion.

**Comment by brianzinn** [comment]
You are correct that `rotationQuaternion` is ignored altogether - I will be able to fix that this weekend.  It requires a small fix in the code generator and a new prop type change handler.

**Comment by brianzinn** [comment]
@ecoinomist - I wrote the code and am experiencing some weird behaviour with setting the rotationQuaternion.  I have opened a bug:
https://forum.babylonjs.com/t/setting-rotationquaternion-affects-absolutescaling/13101

If that is not a bug somehow then I will update my implementation.  The change is ready otherwise.  Will drop an update after I get an answer in the forum.  Cheers.

**Comment by ecoinomist** [comment]
@brianzinn - most likely they will give you an undocumented solution, and close the issue, without fixing it as a bug. happened twice before when I reported issues ;)

**Comment by ecoinomist** [comment]
@brianzinn - I think you are aware of this, but to make sure:
https://doc.babylonjs.com/features/position,_rotation,_scaling#rotationquaternion
Quoting: "When a rotationQuaternion is set the value of rotation is set to (0, 0, 0)."

The `.normalize()` solution posted in the forum works, but it's definitely not documented, even in the how to example above. The `Quaternion.RotationAxis(axis, angle)` method normalizes it internally:
```js
axis.normalize(); // line 2945 in math.vector.js v4.1.0
```

I can confirm the same issue with Quaternion affecting scale when created using `new Quaternion()`. I think it is intentional because they mentioned that a Quaternion may not be used as rotation, but they should have documented it at least.

**Comment by brianzinn** [comment]
I needed to normalize the quaternion that I modified in my calling code 🤦   I'll post an update and NPM release later tonight.

**Comment by brianzinn** [comment]
Here is a sample of how I tested (adding to quaternion this way at a certain point has no effect, but just to make a quick demo).
```jsx
import React, { useState } from 'react'
import { Engine, Scene } from 'react-babylonjs'
import { Vector3, Quaternion } from '@babylonjs/core/Maths/math'
import '../../style.css'

export default { title: 'Babylon Basic' };

export const QuaternionPlayground = () => {
  const [boxQuaternion, setBoxQuaternion] = useState(new Quaternion(0, 0.1, 0, 1));

  return (
    <>
      <Engine antialias adaptToDeviceRatio canvasId='babylonJS' >
        <Scene onPointerDown={() =>{
          setBoxQuaternion(boxQuaternion.add(new Quaternion(0, Math.PI / 10, 0, 0)).normalize());
        }}>
          <freeCamera name='camera1' position={new Vector3(0, 5, -10)} setTarget={[Vector3.Zero()]} />
          <hemisphericLight name='light1' intensity={0.7} direction={Vector3.Up()} />
          <box name='box1' size={2} position={new Vector3(0, 1, 0)} rotationQuaternion={boxQuaternion} />
          <ground name='ground1' width={6} height={6} subdivisions={2} />
        </Scene>
      </Engine>
    </>
  )
}
```

Just deployed an in version 2.2.2
