### ISSUE TITLE
src/customHosts/TargetPropsHandler.ts(15,11): error TS2345

### ISSUE THREAD

**Issue by koin-master** [brianzinn/react-babylonjs#82]
how can i resolve this error?
src/customHosts/TargetPropsHandler.ts(15,11): error TS2345: Argument of type '{ type: string; value: Nullable<AbstractMesh>; changeType: PropChangeType.Primitive; propertyName: string; }' is not assignable to parameter of type 'PropertyUpdate'.
  Object literal may only specify known properties, and 'type' does not exist in type 'PropertyUpdate'.

**type: "BabylonjsCoreMesh",**

**Comment by brianzinn** [comment]
Thanks for reporting. I’Il check later today when I get to a computer. I did some cleanup to reduce file size looks like something was missed.

**Comment by brianzinn** [comment]
thank-you for reporting @koin-master .  I think I didn't even build the last version before publishing...  should be fixed on master and NPM 2.2.4
