### ISSUE TITLE
The Babylon.js Viewer component

### ISSUE THREAD

**Issue by soniapello** [brianzinn/react-babylonjs#9]
Hi Brian 
Do you plan to add some babylon extension in your react-babylonjs like the viewer ? : https://doc.babylonjs.com/extensions/the_babylon_viewer

**Comment by brianzinn** [comment]
Hi Sonia,
I'd be happy to add any missing functionality.  Right now you can view 3D models in your React page with the <Model /> tag:
```jsx
<Model
    sceneFilename="BoomBox.gltf"
    rootUrl = {`${baseUrl}BoomBox/glTF/`}
    position = { new Vector3(0.02, 0, 0) }
  />
```
Any mesh properties (position/rotation/scale/etc) can be used on Model.  You can see running demos on this page - note the demo "with VR" that creates and environment with shadows as well as models:
https://brianzinn.github.io/create-react-app-babylonjs/

**Comment by soniapello** [comment]
Thanks Brian
I just want to know if it's possible to add configuration on model like changing the color of BoomBox or it's texture : https://brianzinn.github.io/create-react-app-babylonjs/withModel
Like they do here : http://punkoffice.com/vfashion/

**Comment by brianzinn** [comment]
You can do what punk office is doing by adding a handler for when the model is loaded:
```jsx
<Model onModelLoaded{loadedModel => {console.log('loaded:', loadedModel}} />
```
If you look in the `main.js` source, you will find that meshes are being enabled/disabled:
```javascript
function changeClothes(item) {
    switch(item) {
        case "top1":
            clothes.top1.setEnabled(true);
            clothes.top2.setEnabled(false);
            break;
      ...
```

If you want to dynamically attach Textures/Materials to meshes that are part of a model declaratively, we could add that Materials/Textures belong to a model and attach perhaps a special propertly like `attachToModelMeshByName("Top1")` - that demo is getting meshes from scene `clothes.top1 = scene.getMeshByName("Top1");`.  Let me know if you wanted to do it completely dynamically and I can add a property (shadow casting uses a similar technique).

**Comment by soniapello** [comment]
Yes completely dynamically would be the best solution.

> I can add a property (shadow casting uses a similar technique).

You would do like [addShadowCaster](https://doc.babylonjs.com/api/classes/babylon.shadowgenerator#addshadowcaster) method to do that ?

**Comment by brianzinn** [comment]
Right now Materials attach to their parent Mesh by default - obviously that doesn't work declaratively for models!  I'll add a property `attachToMeshesByName(meshName: string[])` for declarative assignment.  I don't have time until this weekend, but will add it then.  I will incorporate it into the example repo as well to show others.  Great idea :)

**Comment by soniapello** [comment]
Thank you Brian

**Comment by brianzinn** [comment]
I've added it so that Materials can be assigned to meshes from models.  I have a feeling this may not completely solve the issue as assigning textures to meshes I think does not work yet declaratively.  If you can come up with a full scenario then I can work on writing a declarative version.  Now you can assign StandardMaterials to model meshes by name, so perhaps that is enough...

**Comment by soniapello** [comment]
>  I will incorporate it into the example repo as well to show others

Can you add an onclick change texture or color  example ? like this [one](http://dyo.100netball.com.au/)

**Comment by brianzinn** [comment]
Changing the color of a material can be accomplished by updating state/props.
```jsx
<StandardMaterial name="groundMat" specularColor={ this.props.materialColor} />
```
Any properties on the material will automatically update on the underlying BabylonJS object.  Here are examples in the demo project for updating different properties:
https://brianzinn.github.io/create-react-app-babylonjs/withProps (intensity)
https://brianzinn.github.io/create-react-app-babylonjs/withModel (position)
https://brianzinn.github.io/create-react-app-babylonjs/withVR (rotation)
