### ISSUE TITLE
assignTo multiple properties

### ISSUE THREAD

**Issue by dennemark** [brianzinn/react-babylonjs#90]
Hi,
so far the texture attribute assignTo only allows one string. If I would want to assign the same texture to another property, I currently would have to create a new texture right?
One option to solve this, would be a for loop within the Texture Lifecycle to assign to multiple properties. That would be probably a simple solution.

Alternatively, it would be great to create an instance somehow from a texture and assign it again. A bit similar to what useAssetManager does:
https://github.com/brianzinn/react-babylonjs/blob/3806bc85891d898db09598931f85aa402af51ac3/stories/babylonjs/Textures/image-texture.stories.js

In my case, I want to create a dynamic texture and draw a text on it. Here is some old non-declarative code, that I wanted to use:
```
            //Create dynamic texture
            var textureResolution = {width:512, height:52};
            var textureGround = new BABYLON.DynamicTexture("dynamic texture", textureResolution, scene);  
            //Add text to dynamic texture
            var font = "bold 44px Arial";
            textureGround.drawText("Text",5, 47, font, "lightgray", "black", true, true);
            textureGround.getAlphaFromRGB=true;
            var nameMaterial = new BABYLON.StandardMaterial("Mat", scene);    				
            nameMaterial.diffuseTexture = textureGround;
            nameMaterial.opacityTexture = textureGround;
            nameMesh.material = nameMaterial;
```

**Comment by dennemark** [comment]
Hi Brian,
including the string | string[] part, would be awesome!
Actually I like both ways for different purposes! The first approach is, how I currently would handle it, in the case of an array for assignTo. The second option is a new pattern for me. I would know some additional purposes for that! Assigning the same texture to different materials. Thanks a lot for the input!

**Comment by brianzinn** [comment]
Completely untested (sorry really busy right now), but should work on version `2.2.10` that was just published.
```jsx
const groundRef = useRef(null);
useEffect(() => {
    if (groundRef.current) {
       groundRef.current.hostInstance.drawText(...);
    }
  }, [groundRef.current]
);

return (
  <standardMaterial>
    <textureGround getAlphaFromRGB ref={groundRef} url='...' assignTo={['diffuseTexture', 'opacityTexture']} />
  </standardMaterial>
)
```

Can consider also implementing drawtext, which would be declarative like:
```jsx
// also support object notation that is destructured to args { argName: 'value', ...}
<textureGround ... drawText={["Text",5, 47, font,...]} />
```

I'm considering removing 'hostInstance' from v3, so would assign right to `current` on ref - it's a bit counter intuitive right now.

**Comment by dennemark** [comment]
drawText would be a pretty nice additional extension. But textureGround is a new texture? As far as I know, the drawText needs a dynamicTexture. At least thats the case in the babylonjs docs https://doc.babylonjs.com/how_to/dynamictexture#writing-text

Havent looked into 2.2.10 yet, am also bit busy right now. But hope to be able soon.

**Comment by brianzinn** [comment]
You are right - what I posted would not work!! I hadn't checked the API or read your code snippet properly, but assignTo array should work! :)
