### ISSUE TITLE
material missing transparencyMode

### ISSUE THREAD

**Issue by dennemark** [brianzinn/react-babylonjs#91]
Hi,
the pbrBaseMaterial seems to be the only generated code containing the transparencyMode. Material which is a base class for most other materials, does not contain it apparently. 
https://doc.babylonjs.com/api/classes/babylon.material#transparencymode
Seems like the code generator is missing this property?
I am not familiar enough with react-reconciler to figure this one out, but would be happy to be enlightend :)

current workaround:
```
 const createMaterial=function(material: StandardMaterial){
        material.transparencyMode = StandardMaterial.MATERIAL_ALPHATESTANDBLEND;
    }

<standardMaterial onCreated={createMaterial}></standardMaterial>
```

**Comment by brianzinn** [comment]
I haven't tested it personally, but are you saying that it doesn't work to assign directly?  I do see it in the property checking handler, so would expect this to work:
```jsx
<standardMaterial transparencyMode={StandardMaterial.MATERIAL_ALPHATESTANDBLEND} />
```
If you can confirm that doesn't work (as well as `transparencyMode={3}`) then I will run a proper test on it.

**Comment by dennemark** [comment]
Hi,
I tested it and it does not work for me with both options. 
In generatedProps, the only appearence of transparencyMode is here: https://github.com/brianzinn/react-babylonjs/blob/3806bc85891d898db09598931f85aa402af51ac3/src/generatedProps.ts#L1475
In generatedCode here: https://github.com/brianzinn/react-babylonjs/blob/3806bc85891d898db09598931f85aa402af51ac3/src/generatedCode.ts#L6251

Both times in PBRBaseMaterial, but not the normal Material.

**Comment by brianzinn** [comment]
I suspect it was changed from 4.1 to 4.2 (now in beta):
https://github.com/brianzinn/react-babylonjs/blob/v3/src/generatedCode.ts#L5894

I'm not sure when v3 will roll out - probably right after Babylon 4.2 GA in a couple of weeks.  There are a few breaking changes - many prompted by your question about loaders, which are no longer in `react-babylonjs`, but moved to `react-babylonjs-loaders`, so a bunch of changes coming up :)  I can make a v3 beta NPM, if you're willing to give it a test drive.

**Comment by brianzinn** [comment]
Going to close as it was a change in API - re-open if you feel it's not closed.  Workaround is to use a ref or add handler for `onCreated`, etc.

**Comment by brianzinn** [comment]
@dennemark - should be working on `2.3.0`, which was just generated from 4.2 rc6. I haven't had enough time to get the v3 branch ready in time for 4.2 release :)
