### ISSUE TITLE
react-reconciler not found

### ISSUE THREAD

**Issue by BryBo617** [brianzinn/react-babylonjs#93]
I tried using this library in a CRA project. It is currently failing to compile. I receive the following error.

./node_modules/react-babylonjs/dist/react-babylonjs.js
Module not found: Can't resolve 'react-reconciler' in '/Projects/demo-babylon/node_modules/react-babylonjs/dist'

Update:
I installed the dependency locally and was able to get it to compile. But now It seems the issue is with react-reconciler.
`TypeError: clearContainer is not a function`

    Uncaught TypeError: clearContainer is not a function
    at commitBeforeMutationLifeCycles (react-reconciler.development.js:12427)
    at commitBeforeMutationEffects (react-reconciler.development.js:15881)
    at HTMLUnknownElement.callCallback (react-reconciler.development.js:12184)
    at Object.invokeGuardedCallbackDev (react-reconciler.development.js:12233)
    at invokeGuardedCallback (react-reconciler.development.js:12292)
    at commitRootImpl (react-reconciler.development.js:15652)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority (react-reconciler.development.js:2495)
    at commitRoot (react-reconciler.development.js:15551)
    at performSyncWorkOnRoot (react-reconciler.development.js:14857)
    at react-reconciler.development.js:2546
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority (react-reconciler.development.js:2495)
    at flushSyncCallbackQueueImpl (react-reconciler.development.js:2541)
    at flushSyncCallbackQueue (react-reconciler.development.js:2528)
    at workLoop (scheduler.development.js:590)
    at flushWork (scheduler.development.js:545)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:157)

  | commitBeforeMutationLifeCycles | @ | react-reconciler.development.js:12427
-- | -- | -- | --
  | commitBeforeMutationEffects | @ | react-reconciler.development.js:15881
  | callCallback | @ | react-reconciler.development.js:12184
  | invokeGuardedCallbackDev | @ | react-reconciler.development.js:12233
  | invokeGuardedCallback | @ | react-reconciler.development.js:12292
  | commitRootImpl | @ | react-reconciler.development.js:15652
  | unstable_runWithPriority | @ | scheduler.development.js:646
  | runWithPriority | @ | react-reconciler.development.js:2495
  | commitRoot | @ | react-reconciler.development.js:15551
  | performSyncWorkOnRoot | @ | react-reconciler.development.js:14857
  | (anonymous) | @ | react-reconciler.development.js:2546
  | unstable_runWithPriority | @ | scheduler.development.js:646
  | runWithPriority | @ | react-reconciler.development.js:2495
  | flushSyncCallbackQueueImpl | @ | react-reconciler.development.js:2541
  | flushSyncCallbackQueue | @ | react-reconciler.development.js:2528
  | workLoop | @ | scheduler.development.js:590
  | flushWork | @ | scheduler.development.js:545
  | performWorkUntilDeadline | @ | scheduler.development.js:157

    "@babylonjs/core": "^4.1.0",
    "@babylonjs/gui": "^4.1.0",
    "@babylonjs/inspector": "^4.1.0",
    "@babylonjs/loaders": "^4.1.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "node-sass": "^4.14.1",
    "react": "^17.0.1",
    "react-babylonjs": "^2.2.10",
    "react-dom": "^17.0.1",
    "react-reconciler": "^0.26.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.4"

**Comment by brianzinn** [comment]
i'll need to try out the new React to see if that has been added.  i will have time tonight to fix.  thanks for reporting.

**Comment by BryBo617** [comment]
Thank you. I guess I could downgrade my CRA back to 16.x and try it out.

**Comment by brianzinn** [comment]
These are the method I'm missing on the latest typings `@types/react-reconciler": "^0.18.0"`  - I'll look through the source code on the reconciler to see:
![image](https://user-images.githubusercontent.com/542756/97602424-832f4980-19c8-11eb-8ed8-a3e2d81b0bda.png)

**Comment by brianzinn** [comment]
By looking at the other reconcilers, I think we can just have an empty method - let me patch the reconciler.
https://github.com/facebook/react/pull/18781/files

**Comment by brianzinn** [comment]
@BryBo617 try out version `2.2.12` - just released.  I've moved `react-reconciler` to a regular dependency and added `clearContainer` to the config, but I didn't get a chance to test it or reproduce it yet.

**Comment by BryBo617** [comment]
Thank you! I will update and give it a go.
