### ISSUE TITLE
What's the correct way to switch scenes?

### ISSUE THREAD

**Issue by Flux159** [brianzinn/react-babylonjs#94]
I have an app with multiple scenes and I want to be able to easily switch between scenes based on events (similar to Unity's `LoadScene`). I was able to get something working with two different React Contexts, but it seems like there should be a simpler & consistent way to manage this (almost like a `react-babylonjs-router`?). I was wondering if there was a different method I should be using or if this would require updates to the reconciler code to support in an easier manner.

Example `SceneSwitcherContext.tsx`:
```typescript
export const SceneSwitcherContext = createContext({
  scene: MainMenuScene,
  changeScene: (scene: BabylonScene, newScene: () => JSX.Element, sameScene?: boolean) => {},
} as {
  scene: null | (() => JSX.Element);
  changeScene: (scene: BabylonScene, newScene: () => any, sameScene?: boolean) => void;
});

export const SceneSwitcherContextInternal = createContext({
  scene: MainMenuScene,
  changeScene: (scene: BabylonScene, newScene: () => JSX.Element, sameScene?: boolean) => {},
} as {
  scene: null | (() => JSX.Element);
  changeScene: (scene: BabylonScene, newScene: () => any, sameScene?: boolean) => void;
});
```

Example `MainMenuScene.tsx`:
```typescript
import IntroScene from './IntroScene.tsx';

const MainMenuScene = () => {
  const currentScene = useRef<BabylonScene>();
  const onSceneMount = useCallback((e: SceneEventArgs) => {
    // setup camera, etc.
    // @ts-ignore
    currentScene.current = scene;
  }, []);

  // Note that this works here because it's outside of Scene, if I needed to use a changeScene 
  // function inside of a scene, I would need to use the SceneSwitcherContextInternal context's 
  // changeScene function - effectively duplicating work since the internal context is used 
  // by internal react-babylonjs components inside of a <Scene />
  const context = useContext(SceneSwitcherContext);

  const changeScene = useCallback((scene: any) => {
    if (currentScene.current != null) {
      context.changeScene(currentScene.current, () => scene);
    }
  }, []);

  return (
    <Scene onSceneMount={onSceneMount}>
      <SceneSwitcherContextInternal.Provider value={context}>
        <babylon-button name="test" onPointerUpObservable={() => changeScene(IntroScene)}>...</babylon-button>
      </SceneSwitcherContextInternal.Provider>
    </Scene>
  )
};

export default MainMenuScene;
```

Example `IntroScene.tsx`:
```typescript
const IntroScene = () => {
  return (
    <Scene>
      {...camera setup, etc.}
      <box name="Box" position={new Vector3(0, 0, 0)} />
    </Scene>
  );
};

export default IntroScene;
```

Example top level `App.tsx`:
```typescript
const App = () => {
  // See https://stackoverflow.com/questions/59983813/why-does-the-usestate-hook-invoke-the-initial-state-when-its-a-function-refer
  const [CurrentScene, setScene] = useState<() => JSX.Element>(() => MainMenuScene);

  const changeScene = useCallback((scene: BabylonScene, newScene: () => JSX.Element) => {
    scene.dispose();

    // There's a bug if you try to change scene to the same scene with this
    setScene(newScene);
  }, []);

  const contextValue = {
    scene: CurrentScene,
    changeScene,
  };

  return (
    <SceneSwitcherContext.Provider value={contextValue}>
      <Engine
        canvasId="babyloncanvas"
        antialias
        adaptToDeviceRatio
        touchActionNone
        canvasStyle={{ display: 'block', width: '100%', height: '100%' }}
      >
        <CurrentScene />
      </Engine>
    </SceneSwitcherContext.Provider>
  );
};
```

I was wondering if there was a better way to handle this, specifically:
* Can I avoid using two contexts? I tried creating the external SceneSwitcherContext inside of Engine, but it didn't work properly when trying to use a change scene internally.
* Is there an easier way to handle this type of situation entirely? The code I wrote above is similar to code that I would write for a normal react single page app with react-router - should there be a documented way to do this as part of `react-babylonjs`?

**Comment by brianzinn** [comment]
Thanks for the question and using this project.  I did intentionally keep the `Engine` and `Scene` components separate to be able to support scenarios exactly like this and would really like to help to make it easier for you to do.

The part that throws me off is that you are disposing your scene.  The reason is that if you want to switch a scene it can be done by tricking the ReactDOM renderer:
```
<Engine .../>
   {(state.sceneToShow === 'intro') &&
      <IntroScene />
   }
   {(state.sceneToShow === 'mainMenu') &&
      <MainMenuScene />
   }
</Engine>
```

Not the nicest way, if you have more than two scenes or want fast switching.  At one point I had a way to pass in the engine render loop, so I was thinking that extensibility may be a good way, so your scenes could be loaded at the same time:
https://github.com/brianzinn/react-babylonjs/blob/master/src/Engine.tsx#L103

I could add in a callback like a predicate (lambda) to choose the scene to render?  Maybe something with AssetContainer to keep assets loaded for fast switching otherwise?  The Engine and Scene aren't really part of the "renderer" and should be pretty easy to change to support a lot of functionality - even with your SceneSwitch idea - I hope we could get that running with some changes.  What do you think?

**Comment by Flux159** [comment]
Thanks for the quick response - I think I took the scene.dispose from https://forum.babylonjs.com/t/how-do-i-switch-scenes/2775 - I thought it seemed appropriate since what I really wanted is to remove all meshes, textures, etc. from being rendered from MainMenuScene before loading IntroScene (or any other scene).

My example is actually a bit simpler than other code I already have (with more than 4 scenes) - taking your example a bit further, to be able to switch scenes anywhere, you would need something like this, right?

```
const App = () => {
  const [sceneToShow, setSceneToShow] = useState<string>('mainMenu');

  return (
    <Engine .../>
     {(state.sceneToShow === 'intro') &&
       <IntroScene />
     }
     {(state.sceneToShow === 'mainMenu') &&
       <MainMenuScene />
     }
     {... add more scenes here ...}
  </Engine>
  );
}
```

That would still require similar context code to what I wrote above if a user needed to call setSceneToShow internally of MainMenu or IntroScene right? 

Would it make sense to have a function to change scenes as part of useBabylonEngine or useBabylonScene for usage deeper in nested components? I'm not entirely sure how that would work at the moment & still keep the top level code declarative though.

**Comment by brianzinn** [comment]
Yes, I just tried that out and this works:
```jsx
const FullScreenButton = (props) => {
	const [currentShape, setCurrentShape] = props.shapeState;
	const onClick = _ => {
		setCurrentShape(currentShape => {
			console.log('toggling current shape', currentShape);
			return currentShape === 'spheres' ? 'squares' : 'spheres';
		})
	  };

	return (
		<adtFullscreenUi name='ui'>
			<rectangle name="rect" height='50px' width='150px'>
			<rectangle>
				<babylon-button name="close-icon"
								background="green"
								onPointerDownObservable={onClick}>
				<textBlock text={currentShape}
							fontFamily="FontAwesome" fontStyle="bold"
							fontSize={20} color="white"/>
				</babylon-button>
			</rectangle>
			</rectangle>
		</adtFullscreenUi>
	)
}

const SphereScene = (props) => (
	<Scene>
		<freeCamera name='camera1' position={new Vector3(0, 5, -10)}
					setTarget={[Vector3.Zero()]}/>
		<hemisphericLight
          name='light1'
          direction={Vector3.Up()}
          intensity={0.7}
          diffuse={Color3.Red()}
          specular={Color3.Green()}
          groundColor={Color3.Green()}
        />
		<FullScreenButton shapeState={props.shapeState} />
		{[-4,-2,0,2,4].map(number => (
			<sphere name={`sphere-${number}`} key={number} position={new Vector3(number, 0, 0)} />
		))
		}
	</Scene>
)

const SquareScene = (props) => (
	<Scene>
		<arcRotateCamera
          name="camera1"
          target={Vector3.Zero()}
          alpha={Math.PI / 2}
          beta={Math.PI / 4}
          radius={20}
        />
		<hemisphericLight name='light1' intensity={0.7} direction={Vector3.Up()}/>
		<FullScreenButton shapeState={props.shapeState} />
		{[-4,-2,0,2,4].map(number => (
			<box name={`sphere-${number}`} key={number} position={new Vector3(number, 0, 0)} />
		))
		}
	</Scene>
)

export const ToggleScene = () => {
	const shapeState = useState('spheres');

	return (
		<div style={{flex: 1, display: 'flex'}}>
			<Engine antialias adaptToDeviceRatio canvasId='babylonJS'>
				{(shapeState[0] === 'spheres') &&
					<SphereScene shapeState={shapeState} />
				}
				{(shapeState[0] === 'squares') &&
					<SquareScene shapeState={shapeState} />
				}
			</Engine>
		</div>
	);
}
```

It could be done with a scene switcher doing something similar, but to make it a generic solution could be useful for sure.

The real power of multiple scenes is that you could run them at the same time, but in the render loop just choose which scenes you want to render.  That would allow asset loading or switching to maintain state.

You can render multiple scenes simultaneously like this;
```javascript
engine.runRenderLoop(function () {
  backgroundScene.render();
  foregroundScene.render();
});
```

Or choose the scene (like in a scene chooser, if you didn't want to dispose)
```
engine.runRenderLoop(function () {
// right now this uses a hook, so not the best design for multiple scene rendering...  
chosenScene.render();
});
```
